FROM python:3-alpine

RUN mkdir -p /usr/src/app && adduser -D -H nadiki && chown nadiki:nadiki /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/

RUN pip3 install --no-cache-dir -r requirements.txt

# unfortunately we need to be root on ECS in order to bind to port 443
#USER nadiki
COPY nadiki_registrar nadiki_registrar/
COPY *.flux ./

EXPOSE 443

ENTRYPOINT ["gunicorn"]

#CMD ["-b", "0.0.0.0", "nadiki_registrar.__main__:main()"]
CMD ["--certfile", "/etc/letsencrypt/live/registrar.svc.nadiki.work/fullchain.pem", "--keyfile", "/etc/letsencrypt/live/registrar.svc.nadiki.work/privkey.pem", "nadiki_registrar.__main__:main()", "-b", "0.0.0.0:443"]
