# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from nadiki_registrar.models.cpu import CPU
from nadiki_registrar.models.error import Error
from nadiki_registrar.models.fpga import FPGA
from nadiki_registrar.models.facility_create import FacilityCreate
from nadiki_registrar.models.facility_create_cooling_fluids_inner import FacilityCreateCoolingFluidsInner
from nadiki_registrar.models.facility_impact_assessment import FacilityImpactAssessment
from nadiki_registrar.models.facility_response import FacilityResponse
from nadiki_registrar.models.facility_response_all_of import FacilityResponseAllOf
from nadiki_registrar.models.facility_time_series_config import FacilityTimeSeriesConfig
from nadiki_registrar.models.facility_time_series_data_point import FacilityTimeSeriesDataPoint
from nadiki_registrar.models.facility_time_series_data_point_tags import FacilityTimeSeriesDataPointTags
from nadiki_registrar.models.facility_update import FacilityUpdate
from nadiki_registrar.models.gpu import GPU
from nadiki_registrar.models.list_facilities200_response import ListFacilities200Response
from nadiki_registrar.models.list_racks200_response import ListRacks200Response
from nadiki_registrar.models.list_servers200_response import ListServers200Response
from nadiki_registrar.models.location import Location
from nadiki_registrar.models.rack_create import RackCreate
from nadiki_registrar.models.rack_response import RackResponse
from nadiki_registrar.models.rack_response_all_of import RackResponseAllOf
from nadiki_registrar.models.rack_time_series_config import RackTimeSeriesConfig
from nadiki_registrar.models.rack_time_series_data_point import RackTimeSeriesDataPoint
from nadiki_registrar.models.rack_time_series_data_point_tags import RackTimeSeriesDataPointTags
from nadiki_registrar.models.rack_update import RackUpdate
from nadiki_registrar.models.server_create import ServerCreate
from nadiki_registrar.models.server_impact_assessment import ServerImpactAssessment
from nadiki_registrar.models.server_response import ServerResponse
from nadiki_registrar.models.server_response_all_of import ServerResponseAllOf
from nadiki_registrar.models.server_time_series_config import ServerTimeSeriesConfig
from nadiki_registrar.models.server_time_series_data_point import ServerTimeSeriesDataPoint
from nadiki_registrar.models.server_time_series_data_point_tags import ServerTimeSeriesDataPointTags
from nadiki_registrar.models.server_update import ServerUpdate
from nadiki_registrar.models.storage_device import StorageDevice
