# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.facility_time_series_data_point_labels import FacilityTimeSeriesDataPointLabels
from nadiki_registrar import util

from nadiki_registrar.models.facility_time_series_data_point_labels import FacilityTimeSeriesDataPointLabels  # noqa: E501

class FacilityTimeSeriesDataPoint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, unit=None, granularity_seconds=30, labels=None):  # noqa: E501
        """FacilityTimeSeriesDataPoint - a model defined in OpenAPI

        :param name: The name of this FacilityTimeSeriesDataPoint.  # noqa: E501
        :type name: str
        :param unit: The unit of this FacilityTimeSeriesDataPoint.  # noqa: E501
        :type unit: str
        :param granularity_seconds: The granularity_seconds of this FacilityTimeSeriesDataPoint.  # noqa: E501
        :type granularity_seconds: int
        :param labels: The labels of this FacilityTimeSeriesDataPoint.  # noqa: E501
        :type labels: FacilityTimeSeriesDataPointLabels
        """
        self.openapi_types = {
            'name': str,
            'unit': str,
            'granularity_seconds': int,
            'labels': FacilityTimeSeriesDataPointLabels
        }

        self.attribute_map = {
            'name': 'name',
            'unit': 'unit',
            'granularity_seconds': 'granularitySeconds',
            'labels': 'labels'
        }

        self._name = name
        self._unit = unit
        self._granularity_seconds = granularity_seconds
        self._labels = labels

    @classmethod
    def from_dict(cls, dikt) -> 'FacilityTimeSeriesDataPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacilityTimeSeriesDataPoint of this FacilityTimeSeriesDataPoint.  # noqa: E501
        :rtype: FacilityTimeSeriesDataPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this FacilityTimeSeriesDataPoint.

        Prometheus metric name with unit suffix  # noqa: E501

        :return: The name of this FacilityTimeSeriesDataPoint.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FacilityTimeSeriesDataPoint.

        Prometheus metric name with unit suffix  # noqa: E501

        :param name: The name of this FacilityTimeSeriesDataPoint.
        :type name: str
        """
        allowed_values = ["heatpump_power_consumption_joules", "office_energy_use_joules", "dc_water_usage_cubic_meters", "office_water_usage_cubic_meters", "total_generator_energy_joules", "generator_load_factor_ratio", "grid_transformers_energy_joules", "onsite_renewable_energy_joules", "it_power_usage_level1_joules", "it_power_usage_level2_joules", "renewable_energy_certificates_joules", "grid_emission_factor_grams", "backup_emission_factor_grams", "electricity_source", "pue_1_ratio", "pue_2_ratio"]  # noqa: E501
        if name not in allowed_values:
            raise ValueError(
                "Invalid value for `name` ({0}), must be one of {1}"
                .format(name, allowed_values)
            )

        self._name = name

    @property
    def unit(self):
        """Gets the unit of this FacilityTimeSeriesDataPoint.

        Prometheus metric family  # noqa: E501

        :return: The unit of this FacilityTimeSeriesDataPoint.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this FacilityTimeSeriesDataPoint.

        Prometheus metric family  # noqa: E501

        :param unit: The unit of this FacilityTimeSeriesDataPoint.
        :type unit: str
        """
        allowed_values = ["Time", "Temperature", "Length", "Bytes", "Percent", "Voltage", "Electric current", "Energy", "Power", "Mass"]  # noqa: E501
        if unit not in allowed_values:
            raise ValueError(
                "Invalid value for `unit` ({0}), must be one of {1}"
                .format(unit, allowed_values)
            )

        self._unit = unit

    @property
    def granularity_seconds(self):
        """Gets the granularity_seconds of this FacilityTimeSeriesDataPoint.

        Time series data granularity in seconds  # noqa: E501

        :return: The granularity_seconds of this FacilityTimeSeriesDataPoint.
        :rtype: int
        """
        return self._granularity_seconds

    @granularity_seconds.setter
    def granularity_seconds(self, granularity_seconds):
        """Sets the granularity_seconds of this FacilityTimeSeriesDataPoint.

        Time series data granularity in seconds  # noqa: E501

        :param granularity_seconds: The granularity_seconds of this FacilityTimeSeriesDataPoint.
        :type granularity_seconds: int
        """
        if granularity_seconds is None:
            raise ValueError("Invalid value for `granularity_seconds`, must not be `None`")  # noqa: E501

        self._granularity_seconds = granularity_seconds

    @property
    def labels(self):
        """Gets the labels of this FacilityTimeSeriesDataPoint.


        :return: The labels of this FacilityTimeSeriesDataPoint.
        :rtype: FacilityTimeSeriesDataPointLabels
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this FacilityTimeSeriesDataPoint.


        :param labels: The labels of this FacilityTimeSeriesDataPoint.
        :type labels: FacilityTimeSeriesDataPointLabels
        """
        if labels is None:
            raise ValueError("Invalid value for `labels`, must not be `None`")  # noqa: E501

        self._labels = labels
