# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar import util


class FacilityTimeSeriesDataPointTags(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, facility_id=None, country_code=None):  # noqa: E501
        """FacilityTimeSeriesDataPointTags - a model defined in OpenAPI

        :param facility_id: The facility_id of this FacilityTimeSeriesDataPointTags.  # noqa: E501
        :type facility_id: str
        :param country_code: The country_code of this FacilityTimeSeriesDataPointTags.  # noqa: E501
        :type country_code: str
        """
        self.openapi_types = {
            'facility_id': str,
            'country_code': str
        }

        self.attribute_map = {
            'facility_id': 'facility_id',
            'country_code': 'country_code'
        }

        self._facility_id = facility_id
        self._country_code = country_code

    @classmethod
    def from_dict(cls, dikt) -> 'FacilityTimeSeriesDataPointTags':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacilityTimeSeriesDataPoint_tags of this FacilityTimeSeriesDataPointTags.  # noqa: E501
        :rtype: FacilityTimeSeriesDataPointTags
        """
        return util.deserialize_model(dikt, cls)

    @property
    def facility_id(self):
        """Gets the facility_id of this FacilityTimeSeriesDataPointTags.

        Facility identifier  # noqa: E501

        :return: The facility_id of this FacilityTimeSeriesDataPointTags.
        :rtype: str
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """Sets the facility_id of this FacilityTimeSeriesDataPointTags.

        Facility identifier  # noqa: E501

        :param facility_id: The facility_id of this FacilityTimeSeriesDataPointTags.
        :type facility_id: str
        """
        if facility_id is None:
            raise ValueError("Invalid value for `facility_id`, must not be `None`")  # noqa: E501

        self._facility_id = facility_id

    @property
    def country_code(self):
        """Gets the country_code of this FacilityTimeSeriesDataPointTags.

        ISO 3166-1 alpha-3 country code  # noqa: E501

        :return: The country_code of this FacilityTimeSeriesDataPointTags.
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this FacilityTimeSeriesDataPointTags.

        ISO 3166-1 alpha-3 country code  # noqa: E501

        :param country_code: The country_code of this FacilityTimeSeriesDataPointTags.
        :type country_code: str
        """
        if country_code is None:
            raise ValueError("Invalid value for `country_code`, must not be `None`")  # noqa: E501

        self._country_code = country_code
