# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.facility_time_series_config import FacilityTimeSeriesConfig
from nadiki_registrar import util

from nadiki_registrar.models.facility_time_series_config import FacilityTimeSeriesConfig  # noqa: E501

class FacilityResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, country_code=None, time_series_config=None, created_at=None, updated_at=None):  # noqa: E501
        """FacilityResponseAllOf - a model defined in OpenAPI

        :param id: The id of this FacilityResponseAllOf.  # noqa: E501
        :type id: str
        :param country_code: The country_code of this FacilityResponseAllOf.  # noqa: E501
        :type country_code: str
        :param time_series_config: The time_series_config of this FacilityResponseAllOf.  # noqa: E501
        :type time_series_config: FacilityTimeSeriesConfig
        :param created_at: The created_at of this FacilityResponseAllOf.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this FacilityResponseAllOf.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': str,
            'country_code': str,
            'time_series_config': FacilityTimeSeriesConfig,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'country_code': 'countryCode',
            'time_series_config': 'timeSeriesConfig',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._country_code = country_code
        self._time_series_config = time_series_config
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'FacilityResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacilityResponse_allOf of this FacilityResponseAllOf.  # noqa: E501
        :rtype: FacilityResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this FacilityResponseAllOf.

        Unique facility identifier (format FACILITY-[COUNTRY_CODE]-ID)  # noqa: E501

        :return: The id of this FacilityResponseAllOf.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FacilityResponseAllOf.

        Unique facility identifier (format FACILITY-[COUNTRY_CODE]-ID)  # noqa: E501

        :param id: The id of this FacilityResponseAllOf.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def country_code(self):
        """Gets the country_code of this FacilityResponseAllOf.

        ISO 3166-1 alpha-3 country code derived from location  # noqa: E501

        :return: The country_code of this FacilityResponseAllOf.
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this FacilityResponseAllOf.

        ISO 3166-1 alpha-3 country code derived from location  # noqa: E501

        :param country_code: The country_code of this FacilityResponseAllOf.
        :type country_code: str
        """
        if country_code is None:
            raise ValueError("Invalid value for `country_code`, must not be `None`")  # noqa: E501

        self._country_code = country_code

    @property
    def time_series_config(self):
        """Gets the time_series_config of this FacilityResponseAllOf.


        :return: The time_series_config of this FacilityResponseAllOf.
        :rtype: FacilityTimeSeriesConfig
        """
        return self._time_series_config

    @time_series_config.setter
    def time_series_config(self, time_series_config):
        """Sets the time_series_config of this FacilityResponseAllOf.


        :param time_series_config: The time_series_config of this FacilityResponseAllOf.
        :type time_series_config: FacilityTimeSeriesConfig
        """
        if time_series_config is None:
            raise ValueError("Invalid value for `time_series_config`, must not be `None`")  # noqa: E501

        self._time_series_config = time_series_config

    @property
    def created_at(self):
        """Gets the created_at of this FacilityResponseAllOf.


        :return: The created_at of this FacilityResponseAllOf.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this FacilityResponseAllOf.


        :param created_at: The created_at of this FacilityResponseAllOf.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this FacilityResponseAllOf.


        :return: The updated_at of this FacilityResponseAllOf.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this FacilityResponseAllOf.


        :param updated_at: The updated_at of this FacilityResponseAllOf.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
