# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.facility_create_cooling_fluids_inner import FacilityCreateCoolingFluidsInner
from nadiki_registrar.models.facility_impact_assessment import FacilityImpactAssessment
from nadiki_registrar.models.facility_time_series_config import FacilityTimeSeriesConfig
from nadiki_registrar.models.location import Location
from nadiki_registrar import util

from nadiki_registrar.models.facility_create_cooling_fluids_inner import FacilityCreateCoolingFluidsInner  # noqa: E501
from nadiki_registrar.models.facility_impact_assessment import FacilityImpactAssessment  # noqa: E501
from nadiki_registrar.models.facility_time_series_config import FacilityTimeSeriesConfig  # noqa: E501
from nadiki_registrar.models.location import Location  # noqa: E501

class FacilityResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, location=None, installed_capacity=None, impact_assessment=None, lifetime_facility=20, cooling_fluids=None, maintenance_hours_generator=None, grid_power_feeds=3, design_pue=1.4, tier_level=3, white_space_floors=1, total_space=None, white_space=None, description=None, id=None, country_code=None, time_series_config=None, created_at=None, updated_at=None):  # noqa: E501
        """FacilityResponse - a model defined in OpenAPI

        :param location: The location of this FacilityResponse.  # noqa: E501
        :type location: Location
        :param installed_capacity: The installed_capacity of this FacilityResponse.  # noqa: E501
        :type installed_capacity: float
        :param impact_assessment: The impact_assessment of this FacilityResponse.  # noqa: E501
        :type impact_assessment: FacilityImpactAssessment
        :param lifetime_facility: The lifetime_facility of this FacilityResponse.  # noqa: E501
        :type lifetime_facility: int
        :param cooling_fluids: The cooling_fluids of this FacilityResponse.  # noqa: E501
        :type cooling_fluids: List[FacilityCreateCoolingFluidsInner]
        :param maintenance_hours_generator: The maintenance_hours_generator of this FacilityResponse.  # noqa: E501
        :type maintenance_hours_generator: float
        :param grid_power_feeds: The grid_power_feeds of this FacilityResponse.  # noqa: E501
        :type grid_power_feeds: int
        :param design_pue: The design_pue of this FacilityResponse.  # noqa: E501
        :type design_pue: float
        :param tier_level: The tier_level of this FacilityResponse.  # noqa: E501
        :type tier_level: int
        :param white_space_floors: The white_space_floors of this FacilityResponse.  # noqa: E501
        :type white_space_floors: int
        :param total_space: The total_space of this FacilityResponse.  # noqa: E501
        :type total_space: float
        :param white_space: The white_space of this FacilityResponse.  # noqa: E501
        :type white_space: float
        :param description: The description of this FacilityResponse.  # noqa: E501
        :type description: str
        :param id: The id of this FacilityResponse.  # noqa: E501
        :type id: str
        :param country_code: The country_code of this FacilityResponse.  # noqa: E501
        :type country_code: str
        :param time_series_config: The time_series_config of this FacilityResponse.  # noqa: E501
        :type time_series_config: FacilityTimeSeriesConfig
        :param created_at: The created_at of this FacilityResponse.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this FacilityResponse.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'location': Location,
            'installed_capacity': float,
            'impact_assessment': FacilityImpactAssessment,
            'lifetime_facility': int,
            'cooling_fluids': List[FacilityCreateCoolingFluidsInner],
            'maintenance_hours_generator': float,
            'grid_power_feeds': int,
            'design_pue': float,
            'tier_level': int,
            'white_space_floors': int,
            'total_space': float,
            'white_space': float,
            'description': str,
            'id': str,
            'country_code': str,
            'time_series_config': FacilityTimeSeriesConfig,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'location': 'location',
            'installed_capacity': 'installedCapacity',
            'impact_assessment': 'impactAssessment',
            'lifetime_facility': 'lifetimeFacility',
            'cooling_fluids': 'coolingFluids',
            'maintenance_hours_generator': 'maintenanceHoursGenerator',
            'grid_power_feeds': 'gridPowerFeeds',
            'design_pue': 'designPue',
            'tier_level': 'tierLevel',
            'white_space_floors': 'whiteSpaceFloors',
            'total_space': 'totalSpace',
            'white_space': 'whiteSpace',
            'description': 'description',
            'id': 'id',
            'country_code': 'countryCode',
            'time_series_config': 'timeSeriesConfig',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._location = location
        self._installed_capacity = installed_capacity
        self._impact_assessment = impact_assessment
        self._lifetime_facility = lifetime_facility
        self._cooling_fluids = cooling_fluids
        self._maintenance_hours_generator = maintenance_hours_generator
        self._grid_power_feeds = grid_power_feeds
        self._design_pue = design_pue
        self._tier_level = tier_level
        self._white_space_floors = white_space_floors
        self._total_space = total_space
        self._white_space = white_space
        self._description = description
        self._id = id
        self._country_code = country_code
        self._time_series_config = time_series_config
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'FacilityResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacilityResponse of this FacilityResponse.  # noqa: E501
        :rtype: FacilityResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location(self):
        """Gets the location of this FacilityResponse.


        :return: The location of this FacilityResponse.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this FacilityResponse.


        :param location: The location of this FacilityResponse.
        :type location: Location
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def installed_capacity(self):
        """Gets the installed_capacity of this FacilityResponse.

        Installed/rated power capacity in watts (required for impact assessment scaling)  # noqa: E501

        :return: The installed_capacity of this FacilityResponse.
        :rtype: float
        """
        return self._installed_capacity

    @installed_capacity.setter
    def installed_capacity(self, installed_capacity):
        """Sets the installed_capacity of this FacilityResponse.

        Installed/rated power capacity in watts (required for impact assessment scaling)  # noqa: E501

        :param installed_capacity: The installed_capacity of this FacilityResponse.
        :type installed_capacity: float
        """
        if installed_capacity is None:
            raise ValueError("Invalid value for `installed_capacity`, must not be `None`")  # noqa: E501

        self._installed_capacity = installed_capacity

    @property
    def impact_assessment(self):
        """Gets the impact_assessment of this FacilityResponse.


        :return: The impact_assessment of this FacilityResponse.
        :rtype: FacilityImpactAssessment
        """
        return self._impact_assessment

    @impact_assessment.setter
    def impact_assessment(self, impact_assessment):
        """Sets the impact_assessment of this FacilityResponse.


        :param impact_assessment: The impact_assessment of this FacilityResponse.
        :type impact_assessment: FacilityImpactAssessment
        """

        self._impact_assessment = impact_assessment

    @property
    def lifetime_facility(self):
        """Gets the lifetime_facility of this FacilityResponse.

        Expected lifetime of the facility in years  # noqa: E501

        :return: The lifetime_facility of this FacilityResponse.
        :rtype: int
        """
        return self._lifetime_facility

    @lifetime_facility.setter
    def lifetime_facility(self, lifetime_facility):
        """Sets the lifetime_facility of this FacilityResponse.

        Expected lifetime of the facility in years  # noqa: E501

        :param lifetime_facility: The lifetime_facility of this FacilityResponse.
        :type lifetime_facility: int
        """
        if lifetime_facility is None:
            raise ValueError("Invalid value for `lifetime_facility`, must not be `None`")  # noqa: E501
        if lifetime_facility is not None and lifetime_facility < 1:  # noqa: E501
            raise ValueError("Invalid value for `lifetime_facility`, must be a value greater than or equal to `1`")  # noqa: E501

        self._lifetime_facility = lifetime_facility

    @property
    def cooling_fluids(self):
        """Gets the cooling_fluids of this FacilityResponse.


        :return: The cooling_fluids of this FacilityResponse.
        :rtype: List[FacilityCreateCoolingFluidsInner]
        """
        return self._cooling_fluids

    @cooling_fluids.setter
    def cooling_fluids(self, cooling_fluids):
        """Sets the cooling_fluids of this FacilityResponse.


        :param cooling_fluids: The cooling_fluids of this FacilityResponse.
        :type cooling_fluids: List[FacilityCreateCoolingFluidsInner]
        """

        self._cooling_fluids = cooling_fluids

    @property
    def maintenance_hours_generator(self):
        """Gets the maintenance_hours_generator of this FacilityResponse.

        Annual maintenance runtime hours for generators  # noqa: E501

        :return: The maintenance_hours_generator of this FacilityResponse.
        :rtype: float
        """
        return self._maintenance_hours_generator

    @maintenance_hours_generator.setter
    def maintenance_hours_generator(self, maintenance_hours_generator):
        """Sets the maintenance_hours_generator of this FacilityResponse.

        Annual maintenance runtime hours for generators  # noqa: E501

        :param maintenance_hours_generator: The maintenance_hours_generator of this FacilityResponse.
        :type maintenance_hours_generator: float
        """

        self._maintenance_hours_generator = maintenance_hours_generator

    @property
    def grid_power_feeds(self):
        """Gets the grid_power_feeds of this FacilityResponse.

        Number of physical power feeds  # noqa: E501

        :return: The grid_power_feeds of this FacilityResponse.
        :rtype: int
        """
        return self._grid_power_feeds

    @grid_power_feeds.setter
    def grid_power_feeds(self, grid_power_feeds):
        """Sets the grid_power_feeds of this FacilityResponse.

        Number of physical power feeds  # noqa: E501

        :param grid_power_feeds: The grid_power_feeds of this FacilityResponse.
        :type grid_power_feeds: int
        """
        if grid_power_feeds is not None and grid_power_feeds < 1:  # noqa: E501
            raise ValueError("Invalid value for `grid_power_feeds`, must be a value greater than or equal to `1`")  # noqa: E501

        self._grid_power_feeds = grid_power_feeds

    @property
    def design_pue(self):
        """Gets the design_pue of this FacilityResponse.

        Design Power Usage Effectiveness  # noqa: E501

        :return: The design_pue of this FacilityResponse.
        :rtype: float
        """
        return self._design_pue

    @design_pue.setter
    def design_pue(self, design_pue):
        """Sets the design_pue of this FacilityResponse.

        Design Power Usage Effectiveness  # noqa: E501

        :param design_pue: The design_pue of this FacilityResponse.
        :type design_pue: float
        """
        if design_pue is not None and design_pue < 1:  # noqa: E501
            raise ValueError("Invalid value for `design_pue`, must be a value greater than or equal to `1`")  # noqa: E501

        self._design_pue = design_pue

    @property
    def tier_level(self):
        """Gets the tier_level of this FacilityResponse.

        Certified/rated tier level  # noqa: E501

        :return: The tier_level of this FacilityResponse.
        :rtype: int
        """
        return self._tier_level

    @tier_level.setter
    def tier_level(self, tier_level):
        """Sets the tier_level of this FacilityResponse.

        Certified/rated tier level  # noqa: E501

        :param tier_level: The tier_level of this FacilityResponse.
        :type tier_level: int
        """
        allowed_values = [1, 2, 3, 4]  # noqa: E501
        if tier_level not in allowed_values:
            raise ValueError(
                "Invalid value for `tier_level` ({0}), must be one of {1}"
                .format(tier_level, allowed_values)
            )

        self._tier_level = tier_level

    @property
    def white_space_floors(self):
        """Gets the white_space_floors of this FacilityResponse.

        Number of floors used for white space  # noqa: E501

        :return: The white_space_floors of this FacilityResponse.
        :rtype: int
        """
        return self._white_space_floors

    @white_space_floors.setter
    def white_space_floors(self, white_space_floors):
        """Sets the white_space_floors of this FacilityResponse.

        Number of floors used for white space  # noqa: E501

        :param white_space_floors: The white_space_floors of this FacilityResponse.
        :type white_space_floors: int
        """
        if white_space_floors is not None and white_space_floors < 1:  # noqa: E501
            raise ValueError("Invalid value for `white_space_floors`, must be a value greater than or equal to `1`")  # noqa: E501

        self._white_space_floors = white_space_floors

    @property
    def total_space(self):
        """Gets the total_space of this FacilityResponse.

        Total facility space (m2)  # noqa: E501

        :return: The total_space of this FacilityResponse.
        :rtype: float
        """
        return self._total_space

    @total_space.setter
    def total_space(self, total_space):
        """Sets the total_space of this FacilityResponse.

        Total facility space (m2)  # noqa: E501

        :param total_space: The total_space of this FacilityResponse.
        :type total_space: float
        """

        self._total_space = total_space

    @property
    def white_space(self):
        """Gets the white_space of this FacilityResponse.

        Total white space (m2)  # noqa: E501

        :return: The white_space of this FacilityResponse.
        :rtype: float
        """
        return self._white_space

    @white_space.setter
    def white_space(self, white_space):
        """Sets the white_space of this FacilityResponse.

        Total white space (m2)  # noqa: E501

        :param white_space: The white_space of this FacilityResponse.
        :type white_space: float
        """

        self._white_space = white_space

    @property
    def description(self):
        """Gets the description of this FacilityResponse.

        Textual description ob the facility for informational purposes  # noqa: E501

        :return: The description of this FacilityResponse.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this FacilityResponse.

        Textual description ob the facility for informational purposes  # noqa: E501

        :param description: The description of this FacilityResponse.
        :type description: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this FacilityResponse.

        Unique facility identifier (format FACILITY-[COUNTRY_CODE]-ID)  # noqa: E501

        :return: The id of this FacilityResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FacilityResponse.

        Unique facility identifier (format FACILITY-[COUNTRY_CODE]-ID)  # noqa: E501

        :param id: The id of this FacilityResponse.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def country_code(self):
        """Gets the country_code of this FacilityResponse.

        ISO 3166-1 alpha-3 country code derived from location  # noqa: E501

        :return: The country_code of this FacilityResponse.
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this FacilityResponse.

        ISO 3166-1 alpha-3 country code derived from location  # noqa: E501

        :param country_code: The country_code of this FacilityResponse.
        :type country_code: str
        """
        if country_code is None:
            raise ValueError("Invalid value for `country_code`, must not be `None`")  # noqa: E501

        self._country_code = country_code

    @property
    def time_series_config(self):
        """Gets the time_series_config of this FacilityResponse.


        :return: The time_series_config of this FacilityResponse.
        :rtype: FacilityTimeSeriesConfig
        """
        return self._time_series_config

    @time_series_config.setter
    def time_series_config(self, time_series_config):
        """Sets the time_series_config of this FacilityResponse.


        :param time_series_config: The time_series_config of this FacilityResponse.
        :type time_series_config: FacilityTimeSeriesConfig
        """
        if time_series_config is None:
            raise ValueError("Invalid value for `time_series_config`, must not be `None`")  # noqa: E501

        self._time_series_config = time_series_config

    @property
    def created_at(self):
        """Gets the created_at of this FacilityResponse.


        :return: The created_at of this FacilityResponse.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this FacilityResponse.


        :param created_at: The created_at of this FacilityResponse.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this FacilityResponse.


        :return: The updated_at of this FacilityResponse.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this FacilityResponse.


        :param updated_at: The updated_at of this FacilityResponse.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
