# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar import util


class FacilityImpactAssessment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, climate_change=608571.43, ozone_depletion=4.94, human_toxicity=2622857.14, photochemical_oxidant_formation=2194.29, particulate_matter_formation=2302.86, ionizing_radiation=88000, terrestrial_acidification=4142.86, freshwater_eutrophication=1257.14, marine_eutrophication=720, terrestrial_ecotoxicity=971.43, freshwater_ecotoxicity=29142.86, marine_ecotoxicity=33714.29, agricultural_land_occupation=70571.43, urban_land_occupation=9000, natural_land_transformation=594.29, water_depletion=4485.71, metal_depletion=734285.71, fossil_depletion=1042857.1):  # noqa: E501
        """FacilityImpactAssessment - a model defined in OpenAPI

        :param climate_change: The climate_change of this FacilityImpactAssessment.  # noqa: E501
        :type climate_change: float
        :param ozone_depletion: The ozone_depletion of this FacilityImpactAssessment.  # noqa: E501
        :type ozone_depletion: float
        :param human_toxicity: The human_toxicity of this FacilityImpactAssessment.  # noqa: E501
        :type human_toxicity: float
        :param photochemical_oxidant_formation: The photochemical_oxidant_formation of this FacilityImpactAssessment.  # noqa: E501
        :type photochemical_oxidant_formation: float
        :param particulate_matter_formation: The particulate_matter_formation of this FacilityImpactAssessment.  # noqa: E501
        :type particulate_matter_formation: float
        :param ionizing_radiation: The ionizing_radiation of this FacilityImpactAssessment.  # noqa: E501
        :type ionizing_radiation: float
        :param terrestrial_acidification: The terrestrial_acidification of this FacilityImpactAssessment.  # noqa: E501
        :type terrestrial_acidification: float
        :param freshwater_eutrophication: The freshwater_eutrophication of this FacilityImpactAssessment.  # noqa: E501
        :type freshwater_eutrophication: float
        :param marine_eutrophication: The marine_eutrophication of this FacilityImpactAssessment.  # noqa: E501
        :type marine_eutrophication: float
        :param terrestrial_ecotoxicity: The terrestrial_ecotoxicity of this FacilityImpactAssessment.  # noqa: E501
        :type terrestrial_ecotoxicity: float
        :param freshwater_ecotoxicity: The freshwater_ecotoxicity of this FacilityImpactAssessment.  # noqa: E501
        :type freshwater_ecotoxicity: float
        :param marine_ecotoxicity: The marine_ecotoxicity of this FacilityImpactAssessment.  # noqa: E501
        :type marine_ecotoxicity: float
        :param agricultural_land_occupation: The agricultural_land_occupation of this FacilityImpactAssessment.  # noqa: E501
        :type agricultural_land_occupation: float
        :param urban_land_occupation: The urban_land_occupation of this FacilityImpactAssessment.  # noqa: E501
        :type urban_land_occupation: float
        :param natural_land_transformation: The natural_land_transformation of this FacilityImpactAssessment.  # noqa: E501
        :type natural_land_transformation: float
        :param water_depletion: The water_depletion of this FacilityImpactAssessment.  # noqa: E501
        :type water_depletion: float
        :param metal_depletion: The metal_depletion of this FacilityImpactAssessment.  # noqa: E501
        :type metal_depletion: float
        :param fossil_depletion: The fossil_depletion of this FacilityImpactAssessment.  # noqa: E501
        :type fossil_depletion: float
        """
        self.openapi_types = {
            'climate_change': float,
            'ozone_depletion': float,
            'human_toxicity': float,
            'photochemical_oxidant_formation': float,
            'particulate_matter_formation': float,
            'ionizing_radiation': float,
            'terrestrial_acidification': float,
            'freshwater_eutrophication': float,
            'marine_eutrophication': float,
            'terrestrial_ecotoxicity': float,
            'freshwater_ecotoxicity': float,
            'marine_ecotoxicity': float,
            'agricultural_land_occupation': float,
            'urban_land_occupation': float,
            'natural_land_transformation': float,
            'water_depletion': float,
            'metal_depletion': float,
            'fossil_depletion': float
        }

        self.attribute_map = {
            'climate_change': 'climate_change',
            'ozone_depletion': 'ozone_depletion',
            'human_toxicity': 'human_toxicity',
            'photochemical_oxidant_formation': 'photochemical_oxidant_formation',
            'particulate_matter_formation': 'particulate_matter_formation',
            'ionizing_radiation': 'ionizing_radiation',
            'terrestrial_acidification': 'terrestrial_acidification',
            'freshwater_eutrophication': 'freshwater_eutrophication',
            'marine_eutrophication': 'marine_eutrophication',
            'terrestrial_ecotoxicity': 'terrestrial_ecotoxicity',
            'freshwater_ecotoxicity': 'freshwater_ecotoxicity',
            'marine_ecotoxicity': 'marine_ecotoxicity',
            'agricultural_land_occupation': 'agricultural_land_occupation',
            'urban_land_occupation': 'urban_land_occupation',
            'natural_land_transformation': 'natural_land_transformation',
            'water_depletion': 'water_depletion',
            'metal_depletion': 'metal_depletion',
            'fossil_depletion': 'fossil_depletion'
        }

        self._climate_change = climate_change
        self._ozone_depletion = ozone_depletion
        self._human_toxicity = human_toxicity
        self._photochemical_oxidant_formation = photochemical_oxidant_formation
        self._particulate_matter_formation = particulate_matter_formation
        self._ionizing_radiation = ionizing_radiation
        self._terrestrial_acidification = terrestrial_acidification
        self._freshwater_eutrophication = freshwater_eutrophication
        self._marine_eutrophication = marine_eutrophication
        self._terrestrial_ecotoxicity = terrestrial_ecotoxicity
        self._freshwater_ecotoxicity = freshwater_ecotoxicity
        self._marine_ecotoxicity = marine_ecotoxicity
        self._agricultural_land_occupation = agricultural_land_occupation
        self._urban_land_occupation = urban_land_occupation
        self._natural_land_transformation = natural_land_transformation
        self._water_depletion = water_depletion
        self._metal_depletion = metal_depletion
        self._fossil_depletion = fossil_depletion

    @classmethod
    def from_dict(cls, dikt) -> 'FacilityImpactAssessment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacilityImpactAssessment of this FacilityImpactAssessment.  # noqa: E501
        :rtype: FacilityImpactAssessment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def climate_change(self):
        """Gets the climate_change of this FacilityImpactAssessment.

        Climate change impact in kg CO2 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The climate_change of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._climate_change

    @climate_change.setter
    def climate_change(self, climate_change):
        """Sets the climate_change of this FacilityImpactAssessment.

        Climate change impact in kg CO2 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param climate_change: The climate_change of this FacilityImpactAssessment.
        :type climate_change: float
        """

        self._climate_change = climate_change

    @property
    def ozone_depletion(self):
        """Gets the ozone_depletion of this FacilityImpactAssessment.

        Ozone depletion impact in kg CFC-11 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The ozone_depletion of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._ozone_depletion

    @ozone_depletion.setter
    def ozone_depletion(self, ozone_depletion):
        """Sets the ozone_depletion of this FacilityImpactAssessment.

        Ozone depletion impact in kg CFC-11 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param ozone_depletion: The ozone_depletion of this FacilityImpactAssessment.
        :type ozone_depletion: float
        """

        self._ozone_depletion = ozone_depletion

    @property
    def human_toxicity(self):
        """Gets the human_toxicity of this FacilityImpactAssessment.

        Human toxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The human_toxicity of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._human_toxicity

    @human_toxicity.setter
    def human_toxicity(self, human_toxicity):
        """Sets the human_toxicity of this FacilityImpactAssessment.

        Human toxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param human_toxicity: The human_toxicity of this FacilityImpactAssessment.
        :type human_toxicity: float
        """

        self._human_toxicity = human_toxicity

    @property
    def photochemical_oxidant_formation(self):
        """Gets the photochemical_oxidant_formation of this FacilityImpactAssessment.

        Photochemical oxidant formation impact in kg NMVOC. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The photochemical_oxidant_formation of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._photochemical_oxidant_formation

    @photochemical_oxidant_formation.setter
    def photochemical_oxidant_formation(self, photochemical_oxidant_formation):
        """Sets the photochemical_oxidant_formation of this FacilityImpactAssessment.

        Photochemical oxidant formation impact in kg NMVOC. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param photochemical_oxidant_formation: The photochemical_oxidant_formation of this FacilityImpactAssessment.
        :type photochemical_oxidant_formation: float
        """

        self._photochemical_oxidant_formation = photochemical_oxidant_formation

    @property
    def particulate_matter_formation(self):
        """Gets the particulate_matter_formation of this FacilityImpactAssessment.

        Particulate matter formation impact in kg PM10 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The particulate_matter_formation of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._particulate_matter_formation

    @particulate_matter_formation.setter
    def particulate_matter_formation(self, particulate_matter_formation):
        """Sets the particulate_matter_formation of this FacilityImpactAssessment.

        Particulate matter formation impact in kg PM10 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param particulate_matter_formation: The particulate_matter_formation of this FacilityImpactAssessment.
        :type particulate_matter_formation: float
        """

        self._particulate_matter_formation = particulate_matter_formation

    @property
    def ionizing_radiation(self):
        """Gets the ionizing_radiation of this FacilityImpactAssessment.

        Ionizing radiation impact in kg U235 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The ionizing_radiation of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._ionizing_radiation

    @ionizing_radiation.setter
    def ionizing_radiation(self, ionizing_radiation):
        """Sets the ionizing_radiation of this FacilityImpactAssessment.

        Ionizing radiation impact in kg U235 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param ionizing_radiation: The ionizing_radiation of this FacilityImpactAssessment.
        :type ionizing_radiation: float
        """

        self._ionizing_radiation = ionizing_radiation

    @property
    def terrestrial_acidification(self):
        """Gets the terrestrial_acidification of this FacilityImpactAssessment.

        Terrestrial acidification impact in kg SO2 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The terrestrial_acidification of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._terrestrial_acidification

    @terrestrial_acidification.setter
    def terrestrial_acidification(self, terrestrial_acidification):
        """Sets the terrestrial_acidification of this FacilityImpactAssessment.

        Terrestrial acidification impact in kg SO2 eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param terrestrial_acidification: The terrestrial_acidification of this FacilityImpactAssessment.
        :type terrestrial_acidification: float
        """

        self._terrestrial_acidification = terrestrial_acidification

    @property
    def freshwater_eutrophication(self):
        """Gets the freshwater_eutrophication of this FacilityImpactAssessment.

        Freshwater eutrophication impact in kg P eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The freshwater_eutrophication of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._freshwater_eutrophication

    @freshwater_eutrophication.setter
    def freshwater_eutrophication(self, freshwater_eutrophication):
        """Sets the freshwater_eutrophication of this FacilityImpactAssessment.

        Freshwater eutrophication impact in kg P eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param freshwater_eutrophication: The freshwater_eutrophication of this FacilityImpactAssessment.
        :type freshwater_eutrophication: float
        """

        self._freshwater_eutrophication = freshwater_eutrophication

    @property
    def marine_eutrophication(self):
        """Gets the marine_eutrophication of this FacilityImpactAssessment.

        Marine eutrophication impact in kg N eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The marine_eutrophication of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._marine_eutrophication

    @marine_eutrophication.setter
    def marine_eutrophication(self, marine_eutrophication):
        """Sets the marine_eutrophication of this FacilityImpactAssessment.

        Marine eutrophication impact in kg N eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param marine_eutrophication: The marine_eutrophication of this FacilityImpactAssessment.
        :type marine_eutrophication: float
        """

        self._marine_eutrophication = marine_eutrophication

    @property
    def terrestrial_ecotoxicity(self):
        """Gets the terrestrial_ecotoxicity of this FacilityImpactAssessment.

        Terrestrial ecotoxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The terrestrial_ecotoxicity of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._terrestrial_ecotoxicity

    @terrestrial_ecotoxicity.setter
    def terrestrial_ecotoxicity(self, terrestrial_ecotoxicity):
        """Sets the terrestrial_ecotoxicity of this FacilityImpactAssessment.

        Terrestrial ecotoxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param terrestrial_ecotoxicity: The terrestrial_ecotoxicity of this FacilityImpactAssessment.
        :type terrestrial_ecotoxicity: float
        """

        self._terrestrial_ecotoxicity = terrestrial_ecotoxicity

    @property
    def freshwater_ecotoxicity(self):
        """Gets the freshwater_ecotoxicity of this FacilityImpactAssessment.

        Freshwater ecotoxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The freshwater_ecotoxicity of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._freshwater_ecotoxicity

    @freshwater_ecotoxicity.setter
    def freshwater_ecotoxicity(self, freshwater_ecotoxicity):
        """Sets the freshwater_ecotoxicity of this FacilityImpactAssessment.

        Freshwater ecotoxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param freshwater_ecotoxicity: The freshwater_ecotoxicity of this FacilityImpactAssessment.
        :type freshwater_ecotoxicity: float
        """

        self._freshwater_ecotoxicity = freshwater_ecotoxicity

    @property
    def marine_ecotoxicity(self):
        """Gets the marine_ecotoxicity of this FacilityImpactAssessment.

        Marine ecotoxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The marine_ecotoxicity of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._marine_ecotoxicity

    @marine_ecotoxicity.setter
    def marine_ecotoxicity(self, marine_ecotoxicity):
        """Sets the marine_ecotoxicity of this FacilityImpactAssessment.

        Marine ecotoxicity impact in kg 1,4-DB eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param marine_ecotoxicity: The marine_ecotoxicity of this FacilityImpactAssessment.
        :type marine_ecotoxicity: float
        """

        self._marine_ecotoxicity = marine_ecotoxicity

    @property
    def agricultural_land_occupation(self):
        """Gets the agricultural_land_occupation of this FacilityImpactAssessment.

        Agricultural land occupation impact in m2a. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The agricultural_land_occupation of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._agricultural_land_occupation

    @agricultural_land_occupation.setter
    def agricultural_land_occupation(self, agricultural_land_occupation):
        """Sets the agricultural_land_occupation of this FacilityImpactAssessment.

        Agricultural land occupation impact in m2a. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param agricultural_land_occupation: The agricultural_land_occupation of this FacilityImpactAssessment.
        :type agricultural_land_occupation: float
        """

        self._agricultural_land_occupation = agricultural_land_occupation

    @property
    def urban_land_occupation(self):
        """Gets the urban_land_occupation of this FacilityImpactAssessment.

        Urban land occupation impact in m2a. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The urban_land_occupation of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._urban_land_occupation

    @urban_land_occupation.setter
    def urban_land_occupation(self, urban_land_occupation):
        """Sets the urban_land_occupation of this FacilityImpactAssessment.

        Urban land occupation impact in m2a. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param urban_land_occupation: The urban_land_occupation of this FacilityImpactAssessment.
        :type urban_land_occupation: float
        """

        self._urban_land_occupation = urban_land_occupation

    @property
    def natural_land_transformation(self):
        """Gets the natural_land_transformation of this FacilityImpactAssessment.

        Natural land transformation impact in m2. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The natural_land_transformation of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._natural_land_transformation

    @natural_land_transformation.setter
    def natural_land_transformation(self, natural_land_transformation):
        """Sets the natural_land_transformation of this FacilityImpactAssessment.

        Natural land transformation impact in m2. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param natural_land_transformation: The natural_land_transformation of this FacilityImpactAssessment.
        :type natural_land_transformation: float
        """

        self._natural_land_transformation = natural_land_transformation

    @property
    def water_depletion(self):
        """Gets the water_depletion of this FacilityImpactAssessment.

        Water depletion impact in m3. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The water_depletion of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._water_depletion

    @water_depletion.setter
    def water_depletion(self, water_depletion):
        """Sets the water_depletion of this FacilityImpactAssessment.

        Water depletion impact in m3. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param water_depletion: The water_depletion of this FacilityImpactAssessment.
        :type water_depletion: float
        """

        self._water_depletion = water_depletion

    @property
    def metal_depletion(self):
        """Gets the metal_depletion of this FacilityImpactAssessment.

        Metal depletion impact in kg Fe eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The metal_depletion of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._metal_depletion

    @metal_depletion.setter
    def metal_depletion(self, metal_depletion):
        """Sets the metal_depletion of this FacilityImpactAssessment.

        Metal depletion impact in kg Fe eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param metal_depletion: The metal_depletion of this FacilityImpactAssessment.
        :type metal_depletion: float
        """

        self._metal_depletion = metal_depletion

    @property
    def fossil_depletion(self):
        """Gets the fossil_depletion of this FacilityImpactAssessment.

        Fossil depletion impact in kg oil eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :return: The fossil_depletion of this FacilityImpactAssessment.
        :rtype: float
        """
        return self._fossil_depletion

    @fossil_depletion.setter
    def fossil_depletion(self, fossil_depletion):
        """Sets the fossil_depletion of this FacilityImpactAssessment.

        Fossil depletion impact in kg oil eq. Default derived for a 1 MW data center and scaled according to installedCapacity.  # noqa: E501

        :param fossil_depletion: The fossil_depletion of this FacilityImpactAssessment.
        :type fossil_depletion: float
        """

        self._fossil_depletion = fossil_depletion
