# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar import util


class GPU(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, vendor=None, type=None):  # noqa: E501
        """GPU - a model defined in OpenAPI

        :param vendor: The vendor of this GPU.  # noqa: E501
        :type vendor: str
        :param type: The type of this GPU.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'vendor': str,
            'type': str
        }

        self.attribute_map = {
            'vendor': 'vendor',
            'type': 'type'
        }

        self._vendor = vendor
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'GPU':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GPU of this GPU.  # noqa: E501
        :rtype: GPU
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vendor(self):
        """Gets the vendor of this GPU.

        GPU vendor (e.g., Nvidia, AMD)  # noqa: E501

        :return: The vendor of this GPU.
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this GPU.

        GPU vendor (e.g., Nvidia, AMD)  # noqa: E501

        :param vendor: The vendor of this GPU.
        :type vendor: str
        """
        if vendor is None:
            raise ValueError("Invalid value for `vendor`, must not be `None`")  # noqa: E501

        self._vendor = vendor

    @property
    def type(self):
        """Gets the type of this GPU.

        GPU type identifier  # noqa: E501

        :return: The type of this GPU.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GPU.

        GPU type identifier  # noqa: E501

        :param type: The type of this GPU.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
