# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar import util


class HardDisk(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, vendor=None, capacity=None, type=None):  # noqa: E501
        """HardDisk - a model defined in OpenAPI

        :param vendor: The vendor of this HardDisk.  # noqa: E501
        :type vendor: str
        :param capacity: The capacity of this HardDisk.  # noqa: E501
        :type capacity: float
        :param type: The type of this HardDisk.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'vendor': str,
            'capacity': float,
            'type': str
        }

        self.attribute_map = {
            'vendor': 'vendor',
            'capacity': 'capacity',
            'type': 'type'
        }

        self._vendor = vendor
        self._capacity = capacity
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'HardDisk':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HardDisk of this HardDisk.  # noqa: E501
        :rtype: HardDisk
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vendor(self):
        """Gets the vendor of this HardDisk.

        Disk vendor (e.g., Samsung, Intel)  # noqa: E501

        :return: The vendor of this HardDisk.
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this HardDisk.

        Disk vendor (e.g., Samsung, Intel)  # noqa: E501

        :param vendor: The vendor of this HardDisk.
        :type vendor: str
        """
        if vendor is None:
            raise ValueError("Invalid value for `vendor`, must not be `None`")  # noqa: E501

        self._vendor = vendor

    @property
    def capacity(self):
        """Gets the capacity of this HardDisk.

        Disk capacity in TB  # noqa: E501

        :return: The capacity of this HardDisk.
        :rtype: float
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this HardDisk.

        Disk capacity in TB  # noqa: E501

        :param capacity: The capacity of this HardDisk.
        :type capacity: float
        """
        if capacity is None:
            raise ValueError("Invalid value for `capacity`, must not be `None`")  # noqa: E501

        self._capacity = capacity

    @property
    def type(self):
        """Gets the type of this HardDisk.

        Type of storage device  # noqa: E501

        :return: The type of this HardDisk.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this HardDisk.

        Type of storage device  # noqa: E501

        :param type: The type of this HardDisk.
        :type type: str
        """
        allowed_values = ["NVMe", "SSD", "HDD", "Other"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
