# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.metric_mapping_object_server_power_consumption import MetricMappingObjectServerPowerConsumption
from nadiki_registrar import util

from nadiki_registrar.models.metric_mapping_object_server_power_consumption import MetricMappingObjectServerPowerConsumption  # noqa: E501

class MetricMappingObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, server_power_consumption=None, cpu_utilization=None, cpu_power_consumption=None, cpu_surface_temperature=None, gpu_utilization=None, gpu_power_consumption=None, gpu_memory_utilization=None, fpga_utilization=None, fpga_power_consumption=None, fpga_memory_utilization=None, memory_free=None, memory_available=None, memory_utilization=None, memory_power=None, server_fan_speed=None, network_traffic_received_bytes=None, network_traffic_transmitted_bytes=None, network_traffic_received_packets=None, network_traffic_transmitted_packets=None, storage_read_bytes=None, storage_written_bytes=None, storage_read_completed=None, storage_written_completed=None):  # noqa: E501
        """MetricMappingObject - a model defined in OpenAPI

        :param server_power_consumption: The server_power_consumption of this MetricMappingObject.  # noqa: E501
        :type server_power_consumption: MetricMappingObjectServerPowerConsumption
        :param cpu_utilization: The cpu_utilization of this MetricMappingObject.  # noqa: E501
        :type cpu_utilization: MetricMappingObjectServerPowerConsumption
        :param cpu_power_consumption: The cpu_power_consumption of this MetricMappingObject.  # noqa: E501
        :type cpu_power_consumption: MetricMappingObjectServerPowerConsumption
        :param cpu_surface_temperature: The cpu_surface_temperature of this MetricMappingObject.  # noqa: E501
        :type cpu_surface_temperature: MetricMappingObjectServerPowerConsumption
        :param gpu_utilization: The gpu_utilization of this MetricMappingObject.  # noqa: E501
        :type gpu_utilization: MetricMappingObjectServerPowerConsumption
        :param gpu_power_consumption: The gpu_power_consumption of this MetricMappingObject.  # noqa: E501
        :type gpu_power_consumption: MetricMappingObjectServerPowerConsumption
        :param gpu_memory_utilization: The gpu_memory_utilization of this MetricMappingObject.  # noqa: E501
        :type gpu_memory_utilization: MetricMappingObjectServerPowerConsumption
        :param fpga_utilization: The fpga_utilization of this MetricMappingObject.  # noqa: E501
        :type fpga_utilization: MetricMappingObjectServerPowerConsumption
        :param fpga_power_consumption: The fpga_power_consumption of this MetricMappingObject.  # noqa: E501
        :type fpga_power_consumption: MetricMappingObjectServerPowerConsumption
        :param fpga_memory_utilization: The fpga_memory_utilization of this MetricMappingObject.  # noqa: E501
        :type fpga_memory_utilization: MetricMappingObjectServerPowerConsumption
        :param memory_free: The memory_free of this MetricMappingObject.  # noqa: E501
        :type memory_free: MetricMappingObjectServerPowerConsumption
        :param memory_available: The memory_available of this MetricMappingObject.  # noqa: E501
        :type memory_available: MetricMappingObjectServerPowerConsumption
        :param memory_utilization: The memory_utilization of this MetricMappingObject.  # noqa: E501
        :type memory_utilization: MetricMappingObjectServerPowerConsumption
        :param memory_power: The memory_power of this MetricMappingObject.  # noqa: E501
        :type memory_power: MetricMappingObjectServerPowerConsumption
        :param server_fan_speed: The server_fan_speed of this MetricMappingObject.  # noqa: E501
        :type server_fan_speed: MetricMappingObjectServerPowerConsumption
        :param network_traffic_received_bytes: The network_traffic_received_bytes of this MetricMappingObject.  # noqa: E501
        :type network_traffic_received_bytes: MetricMappingObjectServerPowerConsumption
        :param network_traffic_transmitted_bytes: The network_traffic_transmitted_bytes of this MetricMappingObject.  # noqa: E501
        :type network_traffic_transmitted_bytes: MetricMappingObjectServerPowerConsumption
        :param network_traffic_received_packets: The network_traffic_received_packets of this MetricMappingObject.  # noqa: E501
        :type network_traffic_received_packets: MetricMappingObjectServerPowerConsumption
        :param network_traffic_transmitted_packets: The network_traffic_transmitted_packets of this MetricMappingObject.  # noqa: E501
        :type network_traffic_transmitted_packets: MetricMappingObjectServerPowerConsumption
        :param storage_read_bytes: The storage_read_bytes of this MetricMappingObject.  # noqa: E501
        :type storage_read_bytes: MetricMappingObjectServerPowerConsumption
        :param storage_written_bytes: The storage_written_bytes of this MetricMappingObject.  # noqa: E501
        :type storage_written_bytes: MetricMappingObjectServerPowerConsumption
        :param storage_read_completed: The storage_read_completed of this MetricMappingObject.  # noqa: E501
        :type storage_read_completed: MetricMappingObjectServerPowerConsumption
        :param storage_written_completed: The storage_written_completed of this MetricMappingObject.  # noqa: E501
        :type storage_written_completed: MetricMappingObjectServerPowerConsumption
        """
        self.openapi_types = {
            'server_power_consumption': MetricMappingObjectServerPowerConsumption,
            'cpu_utilization': MetricMappingObjectServerPowerConsumption,
            'cpu_power_consumption': MetricMappingObjectServerPowerConsumption,
            'cpu_surface_temperature': MetricMappingObjectServerPowerConsumption,
            'gpu_utilization': MetricMappingObjectServerPowerConsumption,
            'gpu_power_consumption': MetricMappingObjectServerPowerConsumption,
            'gpu_memory_utilization': MetricMappingObjectServerPowerConsumption,
            'fpga_utilization': MetricMappingObjectServerPowerConsumption,
            'fpga_power_consumption': MetricMappingObjectServerPowerConsumption,
            'fpga_memory_utilization': MetricMappingObjectServerPowerConsumption,
            'memory_free': MetricMappingObjectServerPowerConsumption,
            'memory_available': MetricMappingObjectServerPowerConsumption,
            'memory_utilization': MetricMappingObjectServerPowerConsumption,
            'memory_power': MetricMappingObjectServerPowerConsumption,
            'server_fan_speed': MetricMappingObjectServerPowerConsumption,
            'network_traffic_received_bytes': MetricMappingObjectServerPowerConsumption,
            'network_traffic_transmitted_bytes': MetricMappingObjectServerPowerConsumption,
            'network_traffic_received_packets': MetricMappingObjectServerPowerConsumption,
            'network_traffic_transmitted_packets': MetricMappingObjectServerPowerConsumption,
            'storage_read_bytes': MetricMappingObjectServerPowerConsumption,
            'storage_written_bytes': MetricMappingObjectServerPowerConsumption,
            'storage_read_completed': MetricMappingObjectServerPowerConsumption,
            'storage_written_completed': MetricMappingObjectServerPowerConsumption
        }

        self.attribute_map = {
            'server_power_consumption': 'server_power_consumption',
            'cpu_utilization': 'cpu_utilization',
            'cpu_power_consumption': 'cpu_power_consumption',
            'cpu_surface_temperature': 'cpu_surface_temperature',
            'gpu_utilization': 'gpu_utilization',
            'gpu_power_consumption': 'gpu_power_consumption',
            'gpu_memory_utilization': 'gpu_memory_utilization',
            'fpga_utilization': 'fpga_utilization',
            'fpga_power_consumption': 'fpga_power_consumption',
            'fpga_memory_utilization': 'fpga_memory_utilization',
            'memory_free': 'memory_free',
            'memory_available': 'memory_available',
            'memory_utilization': 'memory_utilization',
            'memory_power': 'memory_power',
            'server_fan_speed': 'server_fan_speed',
            'network_traffic_received_bytes': 'network_traffic_received_bytes',
            'network_traffic_transmitted_bytes': 'network_traffic_transmitted_bytes',
            'network_traffic_received_packets': 'network_traffic_received_packets',
            'network_traffic_transmitted_packets': 'network_traffic_transmitted_packets',
            'storage_read_bytes': 'storage_read_bytes',
            'storage_written_bytes': 'storage_written_bytes',
            'storage_read_completed': 'storage_read_completed',
            'storage_written_completed': 'storage_written_completed'
        }

        self._server_power_consumption = server_power_consumption
        self._cpu_utilization = cpu_utilization
        self._cpu_power_consumption = cpu_power_consumption
        self._cpu_surface_temperature = cpu_surface_temperature
        self._gpu_utilization = gpu_utilization
        self._gpu_power_consumption = gpu_power_consumption
        self._gpu_memory_utilization = gpu_memory_utilization
        self._fpga_utilization = fpga_utilization
        self._fpga_power_consumption = fpga_power_consumption
        self._fpga_memory_utilization = fpga_memory_utilization
        self._memory_free = memory_free
        self._memory_available = memory_available
        self._memory_utilization = memory_utilization
        self._memory_power = memory_power
        self._server_fan_speed = server_fan_speed
        self._network_traffic_received_bytes = network_traffic_received_bytes
        self._network_traffic_transmitted_bytes = network_traffic_transmitted_bytes
        self._network_traffic_received_packets = network_traffic_received_packets
        self._network_traffic_transmitted_packets = network_traffic_transmitted_packets
        self._storage_read_bytes = storage_read_bytes
        self._storage_written_bytes = storage_written_bytes
        self._storage_read_completed = storage_read_completed
        self._storage_written_completed = storage_written_completed

    @classmethod
    def from_dict(cls, dikt) -> 'MetricMappingObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MetricMappingObject of this MetricMappingObject.  # noqa: E501
        :rtype: MetricMappingObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def server_power_consumption(self):
        """Gets the server_power_consumption of this MetricMappingObject.


        :return: The server_power_consumption of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._server_power_consumption

    @server_power_consumption.setter
    def server_power_consumption(self, server_power_consumption):
        """Sets the server_power_consumption of this MetricMappingObject.


        :param server_power_consumption: The server_power_consumption of this MetricMappingObject.
        :type server_power_consumption: MetricMappingObjectServerPowerConsumption
        """

        self._server_power_consumption = server_power_consumption

    @property
    def cpu_utilization(self):
        """Gets the cpu_utilization of this MetricMappingObject.


        :return: The cpu_utilization of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._cpu_utilization

    @cpu_utilization.setter
    def cpu_utilization(self, cpu_utilization):
        """Sets the cpu_utilization of this MetricMappingObject.


        :param cpu_utilization: The cpu_utilization of this MetricMappingObject.
        :type cpu_utilization: MetricMappingObjectServerPowerConsumption
        """

        self._cpu_utilization = cpu_utilization

    @property
    def cpu_power_consumption(self):
        """Gets the cpu_power_consumption of this MetricMappingObject.


        :return: The cpu_power_consumption of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._cpu_power_consumption

    @cpu_power_consumption.setter
    def cpu_power_consumption(self, cpu_power_consumption):
        """Sets the cpu_power_consumption of this MetricMappingObject.


        :param cpu_power_consumption: The cpu_power_consumption of this MetricMappingObject.
        :type cpu_power_consumption: MetricMappingObjectServerPowerConsumption
        """

        self._cpu_power_consumption = cpu_power_consumption

    @property
    def cpu_surface_temperature(self):
        """Gets the cpu_surface_temperature of this MetricMappingObject.


        :return: The cpu_surface_temperature of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._cpu_surface_temperature

    @cpu_surface_temperature.setter
    def cpu_surface_temperature(self, cpu_surface_temperature):
        """Sets the cpu_surface_temperature of this MetricMappingObject.


        :param cpu_surface_temperature: The cpu_surface_temperature of this MetricMappingObject.
        :type cpu_surface_temperature: MetricMappingObjectServerPowerConsumption
        """

        self._cpu_surface_temperature = cpu_surface_temperature

    @property
    def gpu_utilization(self):
        """Gets the gpu_utilization of this MetricMappingObject.


        :return: The gpu_utilization of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._gpu_utilization

    @gpu_utilization.setter
    def gpu_utilization(self, gpu_utilization):
        """Sets the gpu_utilization of this MetricMappingObject.


        :param gpu_utilization: The gpu_utilization of this MetricMappingObject.
        :type gpu_utilization: MetricMappingObjectServerPowerConsumption
        """

        self._gpu_utilization = gpu_utilization

    @property
    def gpu_power_consumption(self):
        """Gets the gpu_power_consumption of this MetricMappingObject.


        :return: The gpu_power_consumption of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._gpu_power_consumption

    @gpu_power_consumption.setter
    def gpu_power_consumption(self, gpu_power_consumption):
        """Sets the gpu_power_consumption of this MetricMappingObject.


        :param gpu_power_consumption: The gpu_power_consumption of this MetricMappingObject.
        :type gpu_power_consumption: MetricMappingObjectServerPowerConsumption
        """

        self._gpu_power_consumption = gpu_power_consumption

    @property
    def gpu_memory_utilization(self):
        """Gets the gpu_memory_utilization of this MetricMappingObject.


        :return: The gpu_memory_utilization of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._gpu_memory_utilization

    @gpu_memory_utilization.setter
    def gpu_memory_utilization(self, gpu_memory_utilization):
        """Sets the gpu_memory_utilization of this MetricMappingObject.


        :param gpu_memory_utilization: The gpu_memory_utilization of this MetricMappingObject.
        :type gpu_memory_utilization: MetricMappingObjectServerPowerConsumption
        """

        self._gpu_memory_utilization = gpu_memory_utilization

    @property
    def fpga_utilization(self):
        """Gets the fpga_utilization of this MetricMappingObject.


        :return: The fpga_utilization of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._fpga_utilization

    @fpga_utilization.setter
    def fpga_utilization(self, fpga_utilization):
        """Sets the fpga_utilization of this MetricMappingObject.


        :param fpga_utilization: The fpga_utilization of this MetricMappingObject.
        :type fpga_utilization: MetricMappingObjectServerPowerConsumption
        """

        self._fpga_utilization = fpga_utilization

    @property
    def fpga_power_consumption(self):
        """Gets the fpga_power_consumption of this MetricMappingObject.


        :return: The fpga_power_consumption of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._fpga_power_consumption

    @fpga_power_consumption.setter
    def fpga_power_consumption(self, fpga_power_consumption):
        """Sets the fpga_power_consumption of this MetricMappingObject.


        :param fpga_power_consumption: The fpga_power_consumption of this MetricMappingObject.
        :type fpga_power_consumption: MetricMappingObjectServerPowerConsumption
        """

        self._fpga_power_consumption = fpga_power_consumption

    @property
    def fpga_memory_utilization(self):
        """Gets the fpga_memory_utilization of this MetricMappingObject.


        :return: The fpga_memory_utilization of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._fpga_memory_utilization

    @fpga_memory_utilization.setter
    def fpga_memory_utilization(self, fpga_memory_utilization):
        """Sets the fpga_memory_utilization of this MetricMappingObject.


        :param fpga_memory_utilization: The fpga_memory_utilization of this MetricMappingObject.
        :type fpga_memory_utilization: MetricMappingObjectServerPowerConsumption
        """

        self._fpga_memory_utilization = fpga_memory_utilization

    @property
    def memory_free(self):
        """Gets the memory_free of this MetricMappingObject.


        :return: The memory_free of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._memory_free

    @memory_free.setter
    def memory_free(self, memory_free):
        """Sets the memory_free of this MetricMappingObject.


        :param memory_free: The memory_free of this MetricMappingObject.
        :type memory_free: MetricMappingObjectServerPowerConsumption
        """

        self._memory_free = memory_free

    @property
    def memory_available(self):
        """Gets the memory_available of this MetricMappingObject.


        :return: The memory_available of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._memory_available

    @memory_available.setter
    def memory_available(self, memory_available):
        """Sets the memory_available of this MetricMappingObject.


        :param memory_available: The memory_available of this MetricMappingObject.
        :type memory_available: MetricMappingObjectServerPowerConsumption
        """

        self._memory_available = memory_available

    @property
    def memory_utilization(self):
        """Gets the memory_utilization of this MetricMappingObject.


        :return: The memory_utilization of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._memory_utilization

    @memory_utilization.setter
    def memory_utilization(self, memory_utilization):
        """Sets the memory_utilization of this MetricMappingObject.


        :param memory_utilization: The memory_utilization of this MetricMappingObject.
        :type memory_utilization: MetricMappingObjectServerPowerConsumption
        """

        self._memory_utilization = memory_utilization

    @property
    def memory_power(self):
        """Gets the memory_power of this MetricMappingObject.


        :return: The memory_power of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._memory_power

    @memory_power.setter
    def memory_power(self, memory_power):
        """Sets the memory_power of this MetricMappingObject.


        :param memory_power: The memory_power of this MetricMappingObject.
        :type memory_power: MetricMappingObjectServerPowerConsumption
        """

        self._memory_power = memory_power

    @property
    def server_fan_speed(self):
        """Gets the server_fan_speed of this MetricMappingObject.


        :return: The server_fan_speed of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._server_fan_speed

    @server_fan_speed.setter
    def server_fan_speed(self, server_fan_speed):
        """Sets the server_fan_speed of this MetricMappingObject.


        :param server_fan_speed: The server_fan_speed of this MetricMappingObject.
        :type server_fan_speed: MetricMappingObjectServerPowerConsumption
        """

        self._server_fan_speed = server_fan_speed

    @property
    def network_traffic_received_bytes(self):
        """Gets the network_traffic_received_bytes of this MetricMappingObject.


        :return: The network_traffic_received_bytes of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._network_traffic_received_bytes

    @network_traffic_received_bytes.setter
    def network_traffic_received_bytes(self, network_traffic_received_bytes):
        """Sets the network_traffic_received_bytes of this MetricMappingObject.


        :param network_traffic_received_bytes: The network_traffic_received_bytes of this MetricMappingObject.
        :type network_traffic_received_bytes: MetricMappingObjectServerPowerConsumption
        """

        self._network_traffic_received_bytes = network_traffic_received_bytes

    @property
    def network_traffic_transmitted_bytes(self):
        """Gets the network_traffic_transmitted_bytes of this MetricMappingObject.


        :return: The network_traffic_transmitted_bytes of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._network_traffic_transmitted_bytes

    @network_traffic_transmitted_bytes.setter
    def network_traffic_transmitted_bytes(self, network_traffic_transmitted_bytes):
        """Sets the network_traffic_transmitted_bytes of this MetricMappingObject.


        :param network_traffic_transmitted_bytes: The network_traffic_transmitted_bytes of this MetricMappingObject.
        :type network_traffic_transmitted_bytes: MetricMappingObjectServerPowerConsumption
        """

        self._network_traffic_transmitted_bytes = network_traffic_transmitted_bytes

    @property
    def network_traffic_received_packets(self):
        """Gets the network_traffic_received_packets of this MetricMappingObject.


        :return: The network_traffic_received_packets of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._network_traffic_received_packets

    @network_traffic_received_packets.setter
    def network_traffic_received_packets(self, network_traffic_received_packets):
        """Sets the network_traffic_received_packets of this MetricMappingObject.


        :param network_traffic_received_packets: The network_traffic_received_packets of this MetricMappingObject.
        :type network_traffic_received_packets: MetricMappingObjectServerPowerConsumption
        """

        self._network_traffic_received_packets = network_traffic_received_packets

    @property
    def network_traffic_transmitted_packets(self):
        """Gets the network_traffic_transmitted_packets of this MetricMappingObject.


        :return: The network_traffic_transmitted_packets of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._network_traffic_transmitted_packets

    @network_traffic_transmitted_packets.setter
    def network_traffic_transmitted_packets(self, network_traffic_transmitted_packets):
        """Sets the network_traffic_transmitted_packets of this MetricMappingObject.


        :param network_traffic_transmitted_packets: The network_traffic_transmitted_packets of this MetricMappingObject.
        :type network_traffic_transmitted_packets: MetricMappingObjectServerPowerConsumption
        """

        self._network_traffic_transmitted_packets = network_traffic_transmitted_packets

    @property
    def storage_read_bytes(self):
        """Gets the storage_read_bytes of this MetricMappingObject.


        :return: The storage_read_bytes of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._storage_read_bytes

    @storage_read_bytes.setter
    def storage_read_bytes(self, storage_read_bytes):
        """Sets the storage_read_bytes of this MetricMappingObject.


        :param storage_read_bytes: The storage_read_bytes of this MetricMappingObject.
        :type storage_read_bytes: MetricMappingObjectServerPowerConsumption
        """

        self._storage_read_bytes = storage_read_bytes

    @property
    def storage_written_bytes(self):
        """Gets the storage_written_bytes of this MetricMappingObject.


        :return: The storage_written_bytes of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._storage_written_bytes

    @storage_written_bytes.setter
    def storage_written_bytes(self, storage_written_bytes):
        """Sets the storage_written_bytes of this MetricMappingObject.


        :param storage_written_bytes: The storage_written_bytes of this MetricMappingObject.
        :type storage_written_bytes: MetricMappingObjectServerPowerConsumption
        """

        self._storage_written_bytes = storage_written_bytes

    @property
    def storage_read_completed(self):
        """Gets the storage_read_completed of this MetricMappingObject.


        :return: The storage_read_completed of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._storage_read_completed

    @storage_read_completed.setter
    def storage_read_completed(self, storage_read_completed):
        """Sets the storage_read_completed of this MetricMappingObject.


        :param storage_read_completed: The storage_read_completed of this MetricMappingObject.
        :type storage_read_completed: MetricMappingObjectServerPowerConsumption
        """

        self._storage_read_completed = storage_read_completed

    @property
    def storage_written_completed(self):
        """Gets the storage_written_completed of this MetricMappingObject.


        :return: The storage_written_completed of this MetricMappingObject.
        :rtype: MetricMappingObjectServerPowerConsumption
        """
        return self._storage_written_completed

    @storage_written_completed.setter
    def storage_written_completed(self, storage_written_completed):
        """Sets the storage_written_completed of this MetricMappingObject.


        :param storage_written_completed: The storage_written_completed of this MetricMappingObject.
        :type storage_written_completed: MetricMappingObjectServerPowerConsumption
        """

        self._storage_written_completed = storage_written_completed
