# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.rack_time_series_data_point_tags import RackTimeSeriesDataPointTags
import re
from nadiki_registrar import util

from nadiki_registrar.models.rack_time_series_data_point_tags import RackTimeSeriesDataPointTags  # noqa: E501
import re  # noqa: E501

class RackTimeSeriesDataPoint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, measurement=None, field=None, granularity_seconds=30, tags=None):  # noqa: E501
        """RackTimeSeriesDataPoint - a model defined in OpenAPI

        :param measurement: The measurement of this RackTimeSeriesDataPoint.  # noqa: E501
        :type measurement: str
        :param field: The field of this RackTimeSeriesDataPoint.  # noqa: E501
        :type field: str
        :param granularity_seconds: The granularity_seconds of this RackTimeSeriesDataPoint.  # noqa: E501
        :type granularity_seconds: int
        :param tags: The tags of this RackTimeSeriesDataPoint.  # noqa: E501
        :type tags: RackTimeSeriesDataPointTags
        """
        self.openapi_types = {
            'measurement': str,
            'field': str,
            'granularity_seconds': int,
            'tags': RackTimeSeriesDataPointTags
        }

        self.attribute_map = {
            'measurement': 'measurement',
            'field': 'field',
            'granularity_seconds': 'granularitySeconds',
            'tags': 'tags'
        }

        self._measurement = measurement
        self._field = field
        self._granularity_seconds = granularity_seconds
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'RackTimeSeriesDataPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RackTimeSeriesDataPoint of this RackTimeSeriesDataPoint.  # noqa: E501
        :rtype: RackTimeSeriesDataPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def measurement(self):
        """Gets the measurement of this RackTimeSeriesDataPoint.

        Name of the Influx measurement  # noqa: E501

        :return: The measurement of this RackTimeSeriesDataPoint.
        :rtype: str
        """
        return self._measurement

    @measurement.setter
    def measurement(self, measurement):
        """Sets the measurement of this RackTimeSeriesDataPoint.

        Name of the Influx measurement  # noqa: E501

        :param measurement: The measurement of this RackTimeSeriesDataPoint.
        :type measurement: str
        """
        allowed_values = ["facility", "rack", "server"]  # noqa: E501
        if measurement not in allowed_values:
            raise ValueError(
                "Invalid value for `measurement` ({0}), must be one of {1}"
                .format(measurement, allowed_values)
            )

        self._measurement = measurement

    @property
    def field(self):
        """Gets the field of this RackTimeSeriesDataPoint.

        Prometheus metric name with unit suffix. For PDU metrics,  the name must follow the pattern 'pdu_N_energy_consumption_joules'  where N is the PDU number (1 to number_of_pdus)   # noqa: E501

        :return: The field of this RackTimeSeriesDataPoint.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this RackTimeSeriesDataPoint.

        Prometheus metric name with unit suffix. For PDU metrics,  the name must follow the pattern 'pdu_N_energy_consumption_joules'  where N is the PDU number (1 to number_of_pdus)   # noqa: E501

        :param field: The field of this RackTimeSeriesDataPoint.
        :type field: str
        """
        if field is None:
            raise ValueError("Invalid value for `field`, must not be `None`")  # noqa: E501
        if field is not None and not re.search(r'^(pdu_[1-9][0-9]*_energy_consumption_joules|inlet_temperature_celsius|outlet_temperature_celsius)$', field):  # noqa: E501
            raise ValueError("Invalid value for `field`, must be a follow pattern or equal to `/^(pdu_[1-9][0-9]*_energy_consumption_joules|inlet_temperature_celsius|outlet_temperature_celsius)$/`")  # noqa: E501

        self._field = field

    @property
    def granularity_seconds(self):
        """Gets the granularity_seconds of this RackTimeSeriesDataPoint.

        Time series data granularity in seconds  # noqa: E501

        :return: The granularity_seconds of this RackTimeSeriesDataPoint.
        :rtype: int
        """
        return self._granularity_seconds

    @granularity_seconds.setter
    def granularity_seconds(self, granularity_seconds):
        """Sets the granularity_seconds of this RackTimeSeriesDataPoint.

        Time series data granularity in seconds  # noqa: E501

        :param granularity_seconds: The granularity_seconds of this RackTimeSeriesDataPoint.
        :type granularity_seconds: int
        """
        if granularity_seconds is None:
            raise ValueError("Invalid value for `granularity_seconds`, must not be `None`")  # noqa: E501

        self._granularity_seconds = granularity_seconds

    @property
    def tags(self):
        """Gets the tags of this RackTimeSeriesDataPoint.


        :return: The tags of this RackTimeSeriesDataPoint.
        :rtype: RackTimeSeriesDataPointTags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this RackTimeSeriesDataPoint.


        :param tags: The tags of this RackTimeSeriesDataPoint.
        :type tags: RackTimeSeriesDataPointTags
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags
