# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.rack_time_series_config import RackTimeSeriesConfig
from nadiki_registrar import util

from nadiki_registrar.models.rack_time_series_config import RackTimeSeriesConfig  # noqa: E501

class RackResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, time_series_config=None, created_at=None, updated_at=None):  # noqa: E501
        """RackResponseAllOf - a model defined in OpenAPI

        :param id: The id of this RackResponseAllOf.  # noqa: E501
        :type id: str
        :param time_series_config: The time_series_config of this RackResponseAllOf.  # noqa: E501
        :type time_series_config: RackTimeSeriesConfig
        :param created_at: The created_at of this RackResponseAllOf.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this RackResponseAllOf.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': str,
            'time_series_config': RackTimeSeriesConfig,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'time_series_config': 'timeSeriesConfig',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._time_series_config = time_series_config
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'RackResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RackResponse_allOf of this RackResponseAllOf.  # noqa: E501
        :rtype: RackResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this RackResponseAllOf.

        Unique rack identifier (format RACK-[FACILITY_ID]-[RACK_ID])  # noqa: E501

        :return: The id of this RackResponseAllOf.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RackResponseAllOf.

        Unique rack identifier (format RACK-[FACILITY_ID]-[RACK_ID])  # noqa: E501

        :param id: The id of this RackResponseAllOf.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def time_series_config(self):
        """Gets the time_series_config of this RackResponseAllOf.


        :return: The time_series_config of this RackResponseAllOf.
        :rtype: RackTimeSeriesConfig
        """
        return self._time_series_config

    @time_series_config.setter
    def time_series_config(self, time_series_config):
        """Sets the time_series_config of this RackResponseAllOf.


        :param time_series_config: The time_series_config of this RackResponseAllOf.
        :type time_series_config: RackTimeSeriesConfig
        """
        if time_series_config is None:
            raise ValueError("Invalid value for `time_series_config`, must not be `None`")  # noqa: E501

        self._time_series_config = time_series_config

    @property
    def created_at(self):
        """Gets the created_at of this RackResponseAllOf.


        :return: The created_at of this RackResponseAllOf.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this RackResponseAllOf.


        :param created_at: The created_at of this RackResponseAllOf.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this RackResponseAllOf.


        :return: The updated_at of this RackResponseAllOf.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this RackResponseAllOf.


        :param updated_at: The updated_at of this RackResponseAllOf.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
