# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar import util


class ServerImpactAssessment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, climate_change=None, primary_energy_use=None, ozone_depletion=None, human_toxicity=None, photochemical_oxidant_formation=None, particulate_matter_formation=None, ionizing_radiation=None, terrestrial_acidification=None, freshwater_eutrophication=None, marine_eutrophication=None, terrestrial_ecotoxicity=None, freshwater_ecotoxicity=None, marine_ecotoxicity=None, agricultural_land_occupation=None, urban_land_occupation=None, natural_land_transformation=None, abiotic_depletion_potential=None):  # noqa: E501
        """ServerImpactAssessment - a model defined in OpenAPI

        :param climate_change: The climate_change of this ServerImpactAssessment.  # noqa: E501
        :type climate_change: float
        :param primary_energy_use: The primary_energy_use of this ServerImpactAssessment.  # noqa: E501
        :type primary_energy_use: float
        :param ozone_depletion: The ozone_depletion of this ServerImpactAssessment.  # noqa: E501
        :type ozone_depletion: float
        :param human_toxicity: The human_toxicity of this ServerImpactAssessment.  # noqa: E501
        :type human_toxicity: float
        :param photochemical_oxidant_formation: The photochemical_oxidant_formation of this ServerImpactAssessment.  # noqa: E501
        :type photochemical_oxidant_formation: float
        :param particulate_matter_formation: The particulate_matter_formation of this ServerImpactAssessment.  # noqa: E501
        :type particulate_matter_formation: float
        :param ionizing_radiation: The ionizing_radiation of this ServerImpactAssessment.  # noqa: E501
        :type ionizing_radiation: float
        :param terrestrial_acidification: The terrestrial_acidification of this ServerImpactAssessment.  # noqa: E501
        :type terrestrial_acidification: float
        :param freshwater_eutrophication: The freshwater_eutrophication of this ServerImpactAssessment.  # noqa: E501
        :type freshwater_eutrophication: float
        :param marine_eutrophication: The marine_eutrophication of this ServerImpactAssessment.  # noqa: E501
        :type marine_eutrophication: float
        :param terrestrial_ecotoxicity: The terrestrial_ecotoxicity of this ServerImpactAssessment.  # noqa: E501
        :type terrestrial_ecotoxicity: float
        :param freshwater_ecotoxicity: The freshwater_ecotoxicity of this ServerImpactAssessment.  # noqa: E501
        :type freshwater_ecotoxicity: float
        :param marine_ecotoxicity: The marine_ecotoxicity of this ServerImpactAssessment.  # noqa: E501
        :type marine_ecotoxicity: float
        :param agricultural_land_occupation: The agricultural_land_occupation of this ServerImpactAssessment.  # noqa: E501
        :type agricultural_land_occupation: float
        :param urban_land_occupation: The urban_land_occupation of this ServerImpactAssessment.  # noqa: E501
        :type urban_land_occupation: float
        :param natural_land_transformation: The natural_land_transformation of this ServerImpactAssessment.  # noqa: E501
        :type natural_land_transformation: float
        :param abiotic_depletion_potential: The abiotic_depletion_potential of this ServerImpactAssessment.  # noqa: E501
        :type abiotic_depletion_potential: float
        """
        self.openapi_types = {
            'climate_change': float,
            'primary_energy_use': float,
            'ozone_depletion': float,
            'human_toxicity': float,
            'photochemical_oxidant_formation': float,
            'particulate_matter_formation': float,
            'ionizing_radiation': float,
            'terrestrial_acidification': float,
            'freshwater_eutrophication': float,
            'marine_eutrophication': float,
            'terrestrial_ecotoxicity': float,
            'freshwater_ecotoxicity': float,
            'marine_ecotoxicity': float,
            'agricultural_land_occupation': float,
            'urban_land_occupation': float,
            'natural_land_transformation': float,
            'abiotic_depletion_potential': float
        }

        self.attribute_map = {
            'climate_change': 'climate_change',
            'primary_energy_use': 'primary_energy_use',
            'ozone_depletion': 'ozone_depletion',
            'human_toxicity': 'human_toxicity',
            'photochemical_oxidant_formation': 'photochemical_oxidant_formation',
            'particulate_matter_formation': 'particulate_matter_formation',
            'ionizing_radiation': 'ionizing_radiation',
            'terrestrial_acidification': 'terrestrial_acidification',
            'freshwater_eutrophication': 'freshwater_eutrophication',
            'marine_eutrophication': 'marine_eutrophication',
            'terrestrial_ecotoxicity': 'terrestrial_ecotoxicity',
            'freshwater_ecotoxicity': 'freshwater_ecotoxicity',
            'marine_ecotoxicity': 'marine_ecotoxicity',
            'agricultural_land_occupation': 'agricultural_land_occupation',
            'urban_land_occupation': 'urban_land_occupation',
            'natural_land_transformation': 'natural_land_transformation',
            'abiotic_depletion_potential': 'abiotic_depletion_potential'
        }

        self._climate_change = climate_change
        self._primary_energy_use = primary_energy_use
        self._ozone_depletion = ozone_depletion
        self._human_toxicity = human_toxicity
        self._photochemical_oxidant_formation = photochemical_oxidant_formation
        self._particulate_matter_formation = particulate_matter_formation
        self._ionizing_radiation = ionizing_radiation
        self._terrestrial_acidification = terrestrial_acidification
        self._freshwater_eutrophication = freshwater_eutrophication
        self._marine_eutrophication = marine_eutrophication
        self._terrestrial_ecotoxicity = terrestrial_ecotoxicity
        self._freshwater_ecotoxicity = freshwater_ecotoxicity
        self._marine_ecotoxicity = marine_ecotoxicity
        self._agricultural_land_occupation = agricultural_land_occupation
        self._urban_land_occupation = urban_land_occupation
        self._natural_land_transformation = natural_land_transformation
        self._abiotic_depletion_potential = abiotic_depletion_potential

    @classmethod
    def from_dict(cls, dikt) -> 'ServerImpactAssessment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerImpactAssessment of this ServerImpactAssessment.  # noqa: E501
        :rtype: ServerImpactAssessment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def climate_change(self):
        """Gets the climate_change of this ServerImpactAssessment.

        Climate change impact in kg CO2 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The climate_change of this ServerImpactAssessment.
        :rtype: float
        """
        return self._climate_change

    @climate_change.setter
    def climate_change(self, climate_change):
        """Sets the climate_change of this ServerImpactAssessment.

        Climate change impact in kg CO2 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param climate_change: The climate_change of this ServerImpactAssessment.
        :type climate_change: float
        """

        self._climate_change = climate_change

    @property
    def primary_energy_use(self):
        """Gets the primary_energy_use of this ServerImpactAssessment.

        Energy used to manufacture the server (kWh). If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The primary_energy_use of this ServerImpactAssessment.
        :rtype: float
        """
        return self._primary_energy_use

    @primary_energy_use.setter
    def primary_energy_use(self, primary_energy_use):
        """Sets the primary_energy_use of this ServerImpactAssessment.

        Energy used to manufacture the server (kWh). If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param primary_energy_use: The primary_energy_use of this ServerImpactAssessment.
        :type primary_energy_use: float
        """

        self._primary_energy_use = primary_energy_use

    @property
    def ozone_depletion(self):
        """Gets the ozone_depletion of this ServerImpactAssessment.

        Ozone depletion impact in kg CFC-11 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The ozone_depletion of this ServerImpactAssessment.
        :rtype: float
        """
        return self._ozone_depletion

    @ozone_depletion.setter
    def ozone_depletion(self, ozone_depletion):
        """Sets the ozone_depletion of this ServerImpactAssessment.

        Ozone depletion impact in kg CFC-11 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param ozone_depletion: The ozone_depletion of this ServerImpactAssessment.
        :type ozone_depletion: float
        """

        self._ozone_depletion = ozone_depletion

    @property
    def human_toxicity(self):
        """Gets the human_toxicity of this ServerImpactAssessment.

        Human toxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The human_toxicity of this ServerImpactAssessment.
        :rtype: float
        """
        return self._human_toxicity

    @human_toxicity.setter
    def human_toxicity(self, human_toxicity):
        """Sets the human_toxicity of this ServerImpactAssessment.

        Human toxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param human_toxicity: The human_toxicity of this ServerImpactAssessment.
        :type human_toxicity: float
        """

        self._human_toxicity = human_toxicity

    @property
    def photochemical_oxidant_formation(self):
        """Gets the photochemical_oxidant_formation of this ServerImpactAssessment.

        Photochemical oxidant formation impact in kg NMVOC. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The photochemical_oxidant_formation of this ServerImpactAssessment.
        :rtype: float
        """
        return self._photochemical_oxidant_formation

    @photochemical_oxidant_formation.setter
    def photochemical_oxidant_formation(self, photochemical_oxidant_formation):
        """Sets the photochemical_oxidant_formation of this ServerImpactAssessment.

        Photochemical oxidant formation impact in kg NMVOC. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param photochemical_oxidant_formation: The photochemical_oxidant_formation of this ServerImpactAssessment.
        :type photochemical_oxidant_formation: float
        """

        self._photochemical_oxidant_formation = photochemical_oxidant_formation

    @property
    def particulate_matter_formation(self):
        """Gets the particulate_matter_formation of this ServerImpactAssessment.

        Particulate matter formation impact in kg PM10 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The particulate_matter_formation of this ServerImpactAssessment.
        :rtype: float
        """
        return self._particulate_matter_formation

    @particulate_matter_formation.setter
    def particulate_matter_formation(self, particulate_matter_formation):
        """Sets the particulate_matter_formation of this ServerImpactAssessment.

        Particulate matter formation impact in kg PM10 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param particulate_matter_formation: The particulate_matter_formation of this ServerImpactAssessment.
        :type particulate_matter_formation: float
        """

        self._particulate_matter_formation = particulate_matter_formation

    @property
    def ionizing_radiation(self):
        """Gets the ionizing_radiation of this ServerImpactAssessment.

        Ionizing radiation impact in kg U235 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The ionizing_radiation of this ServerImpactAssessment.
        :rtype: float
        """
        return self._ionizing_radiation

    @ionizing_radiation.setter
    def ionizing_radiation(self, ionizing_radiation):
        """Sets the ionizing_radiation of this ServerImpactAssessment.

        Ionizing radiation impact in kg U235 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param ionizing_radiation: The ionizing_radiation of this ServerImpactAssessment.
        :type ionizing_radiation: float
        """

        self._ionizing_radiation = ionizing_radiation

    @property
    def terrestrial_acidification(self):
        """Gets the terrestrial_acidification of this ServerImpactAssessment.

        Terrestrial acidification impact in kg SO2 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The terrestrial_acidification of this ServerImpactAssessment.
        :rtype: float
        """
        return self._terrestrial_acidification

    @terrestrial_acidification.setter
    def terrestrial_acidification(self, terrestrial_acidification):
        """Sets the terrestrial_acidification of this ServerImpactAssessment.

        Terrestrial acidification impact in kg SO2 eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param terrestrial_acidification: The terrestrial_acidification of this ServerImpactAssessment.
        :type terrestrial_acidification: float
        """

        self._terrestrial_acidification = terrestrial_acidification

    @property
    def freshwater_eutrophication(self):
        """Gets the freshwater_eutrophication of this ServerImpactAssessment.

        Freshwater eutrophication impact in kg P eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The freshwater_eutrophication of this ServerImpactAssessment.
        :rtype: float
        """
        return self._freshwater_eutrophication

    @freshwater_eutrophication.setter
    def freshwater_eutrophication(self, freshwater_eutrophication):
        """Sets the freshwater_eutrophication of this ServerImpactAssessment.

        Freshwater eutrophication impact in kg P eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param freshwater_eutrophication: The freshwater_eutrophication of this ServerImpactAssessment.
        :type freshwater_eutrophication: float
        """

        self._freshwater_eutrophication = freshwater_eutrophication

    @property
    def marine_eutrophication(self):
        """Gets the marine_eutrophication of this ServerImpactAssessment.

        Marine eutrophication impact in kg N eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The marine_eutrophication of this ServerImpactAssessment.
        :rtype: float
        """
        return self._marine_eutrophication

    @marine_eutrophication.setter
    def marine_eutrophication(self, marine_eutrophication):
        """Sets the marine_eutrophication of this ServerImpactAssessment.

        Marine eutrophication impact in kg N eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param marine_eutrophication: The marine_eutrophication of this ServerImpactAssessment.
        :type marine_eutrophication: float
        """

        self._marine_eutrophication = marine_eutrophication

    @property
    def terrestrial_ecotoxicity(self):
        """Gets the terrestrial_ecotoxicity of this ServerImpactAssessment.

        Terrestrial ecotoxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The terrestrial_ecotoxicity of this ServerImpactAssessment.
        :rtype: float
        """
        return self._terrestrial_ecotoxicity

    @terrestrial_ecotoxicity.setter
    def terrestrial_ecotoxicity(self, terrestrial_ecotoxicity):
        """Sets the terrestrial_ecotoxicity of this ServerImpactAssessment.

        Terrestrial ecotoxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param terrestrial_ecotoxicity: The terrestrial_ecotoxicity of this ServerImpactAssessment.
        :type terrestrial_ecotoxicity: float
        """

        self._terrestrial_ecotoxicity = terrestrial_ecotoxicity

    @property
    def freshwater_ecotoxicity(self):
        """Gets the freshwater_ecotoxicity of this ServerImpactAssessment.

        Freshwater ecotoxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The freshwater_ecotoxicity of this ServerImpactAssessment.
        :rtype: float
        """
        return self._freshwater_ecotoxicity

    @freshwater_ecotoxicity.setter
    def freshwater_ecotoxicity(self, freshwater_ecotoxicity):
        """Sets the freshwater_ecotoxicity of this ServerImpactAssessment.

        Freshwater ecotoxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param freshwater_ecotoxicity: The freshwater_ecotoxicity of this ServerImpactAssessment.
        :type freshwater_ecotoxicity: float
        """

        self._freshwater_ecotoxicity = freshwater_ecotoxicity

    @property
    def marine_ecotoxicity(self):
        """Gets the marine_ecotoxicity of this ServerImpactAssessment.

        Marine ecotoxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The marine_ecotoxicity of this ServerImpactAssessment.
        :rtype: float
        """
        return self._marine_ecotoxicity

    @marine_ecotoxicity.setter
    def marine_ecotoxicity(self, marine_ecotoxicity):
        """Sets the marine_ecotoxicity of this ServerImpactAssessment.

        Marine ecotoxicity impact in kg 1,4-DB eq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param marine_ecotoxicity: The marine_ecotoxicity of this ServerImpactAssessment.
        :type marine_ecotoxicity: float
        """

        self._marine_ecotoxicity = marine_ecotoxicity

    @property
    def agricultural_land_occupation(self):
        """Gets the agricultural_land_occupation of this ServerImpactAssessment.

        Agricultural land occupation impact in m2a. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The agricultural_land_occupation of this ServerImpactAssessment.
        :rtype: float
        """
        return self._agricultural_land_occupation

    @agricultural_land_occupation.setter
    def agricultural_land_occupation(self, agricultural_land_occupation):
        """Sets the agricultural_land_occupation of this ServerImpactAssessment.

        Agricultural land occupation impact in m2a. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param agricultural_land_occupation: The agricultural_land_occupation of this ServerImpactAssessment.
        :type agricultural_land_occupation: float
        """

        self._agricultural_land_occupation = agricultural_land_occupation

    @property
    def urban_land_occupation(self):
        """Gets the urban_land_occupation of this ServerImpactAssessment.

        Urban land occupation impact in m2a. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The urban_land_occupation of this ServerImpactAssessment.
        :rtype: float
        """
        return self._urban_land_occupation

    @urban_land_occupation.setter
    def urban_land_occupation(self, urban_land_occupation):
        """Sets the urban_land_occupation of this ServerImpactAssessment.

        Urban land occupation impact in m2a. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param urban_land_occupation: The urban_land_occupation of this ServerImpactAssessment.
        :type urban_land_occupation: float
        """

        self._urban_land_occupation = urban_land_occupation

    @property
    def natural_land_transformation(self):
        """Gets the natural_land_transformation of this ServerImpactAssessment.

        Natural land transformation impact in m2. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The natural_land_transformation of this ServerImpactAssessment.
        :rtype: float
        """
        return self._natural_land_transformation

    @natural_land_transformation.setter
    def natural_land_transformation(self, natural_land_transformation):
        """Sets the natural_land_transformation of this ServerImpactAssessment.

        Natural land transformation impact in m2. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param natural_land_transformation: The natural_land_transformation of this ServerImpactAssessment.
        :type natural_land_transformation: float
        """

        self._natural_land_transformation = natural_land_transformation

    @property
    def abiotic_depletion_potential(self):
        """Gets the abiotic_depletion_potential of this ServerImpactAssessment.

        Resource depletion in kgSbeq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :return: The abiotic_depletion_potential of this ServerImpactAssessment.
        :rtype: float
        """
        return self._abiotic_depletion_potential

    @abiotic_depletion_potential.setter
    def abiotic_depletion_potential(self, abiotic_depletion_potential):
        """Sets the abiotic_depletion_potential of this ServerImpactAssessment.

        Resource depletion in kgSbeq. If left blank, will be retrieved from Boavizta API according to server specifications.  # noqa: E501

        :param abiotic_depletion_potential: The abiotic_depletion_potential of this ServerImpactAssessment.
        :type abiotic_depletion_potential: float
        """

        self._abiotic_depletion_potential = abiotic_depletion_potential
