# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.cpu import CPU
from nadiki_registrar.models.fpga import FPGA
from nadiki_registrar.models.gpu import GPU
from nadiki_registrar.models.server_impact_assessment import ServerImpactAssessment
from nadiki_registrar.models.storage_device import StorageDevice
from nadiki_registrar import util

from nadiki_registrar.models.cpu import CPU  # noqa: E501
from nadiki_registrar.models.fpga import FPGA  # noqa: E501
from nadiki_registrar.models.gpu import GPU  # noqa: E501
from nadiki_registrar.models.server_impact_assessment import ServerImpactAssessment  # noqa: E501
from nadiki_registrar.models.storage_device import StorageDevice  # noqa: E501

class ServerCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, facility_id=None, rack_id=None, impact_assessment=None, rated_power=None, total_cpu_sockets=2, expected_lifetime=3, installed_cpus=None, number_of_psus=2, total_installed_memory=None, number_of_memory_units=None, storage_devices=None, installed_gpus=None, installed_fpgas=None, product_passport=None, cooling_type='air', description=None):  # noqa: E501
        """ServerCreate - a model defined in OpenAPI

        :param facility_id: The facility_id of this ServerCreate.  # noqa: E501
        :type facility_id: str
        :param rack_id: The rack_id of this ServerCreate.  # noqa: E501
        :type rack_id: str
        :param impact_assessment: The impact_assessment of this ServerCreate.  # noqa: E501
        :type impact_assessment: ServerImpactAssessment
        :param rated_power: The rated_power of this ServerCreate.  # noqa: E501
        :type rated_power: float
        :param total_cpu_sockets: The total_cpu_sockets of this ServerCreate.  # noqa: E501
        :type total_cpu_sockets: int
        :param expected_lifetime: The expected_lifetime of this ServerCreate.  # noqa: E501
        :type expected_lifetime: int
        :param installed_cpus: The installed_cpus of this ServerCreate.  # noqa: E501
        :type installed_cpus: List[CPU]
        :param number_of_psus: The number_of_psus of this ServerCreate.  # noqa: E501
        :type number_of_psus: int
        :param total_installed_memory: The total_installed_memory of this ServerCreate.  # noqa: E501
        :type total_installed_memory: int
        :param number_of_memory_units: The number_of_memory_units of this ServerCreate.  # noqa: E501
        :type number_of_memory_units: int
        :param storage_devices: The storage_devices of this ServerCreate.  # noqa: E501
        :type storage_devices: List[StorageDevice]
        :param installed_gpus: The installed_gpus of this ServerCreate.  # noqa: E501
        :type installed_gpus: List[GPU]
        :param installed_fpgas: The installed_fpgas of this ServerCreate.  # noqa: E501
        :type installed_fpgas: List[FPGA]
        :param product_passport: The product_passport of this ServerCreate.  # noqa: E501
        :type product_passport: object
        :param cooling_type: The cooling_type of this ServerCreate.  # noqa: E501
        :type cooling_type: str
        :param description: The description of this ServerCreate.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'facility_id': str,
            'rack_id': str,
            'impact_assessment': ServerImpactAssessment,
            'rated_power': float,
            'total_cpu_sockets': int,
            'expected_lifetime': int,
            'installed_cpus': List[CPU],
            'number_of_psus': int,
            'total_installed_memory': int,
            'number_of_memory_units': int,
            'storage_devices': List[StorageDevice],
            'installed_gpus': List[GPU],
            'installed_fpgas': List[FPGA],
            'product_passport': object,
            'cooling_type': str,
            'description': str
        }

        self.attribute_map = {
            'facility_id': 'facility_id',
            'rack_id': 'rack_id',
            'impact_assessment': 'impactAssessment',
            'rated_power': 'rated_power',
            'total_cpu_sockets': 'total_cpu_sockets',
            'expected_lifetime': 'expected_lifetime',
            'installed_cpus': 'installed_cpus',
            'number_of_psus': 'number_of_psus',
            'total_installed_memory': 'total_installed_memory',
            'number_of_memory_units': 'number_of_memory_units',
            'storage_devices': 'storage_devices',
            'installed_gpus': 'installed_gpus',
            'installed_fpgas': 'installed_fpgas',
            'product_passport': 'product_passport',
            'cooling_type': 'cooling_type',
            'description': 'description'
        }

        self._facility_id = facility_id
        self._rack_id = rack_id
        self._impact_assessment = impact_assessment
        self._rated_power = rated_power
        self._total_cpu_sockets = total_cpu_sockets
        self._expected_lifetime = expected_lifetime
        self._installed_cpus = installed_cpus
        self._number_of_psus = number_of_psus
        self._total_installed_memory = total_installed_memory
        self._number_of_memory_units = number_of_memory_units
        self._storage_devices = storage_devices
        self._installed_gpus = installed_gpus
        self._installed_fpgas = installed_fpgas
        self._product_passport = product_passport
        self._cooling_type = cooling_type
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'ServerCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerCreate of this ServerCreate.  # noqa: E501
        :rtype: ServerCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def facility_id(self):
        """Gets the facility_id of this ServerCreate.

        ID of the facility where the server is located  # noqa: E501

        :return: The facility_id of this ServerCreate.
        :rtype: str
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """Sets the facility_id of this ServerCreate.

        ID of the facility where the server is located  # noqa: E501

        :param facility_id: The facility_id of this ServerCreate.
        :type facility_id: str
        """
        if facility_id is None:
            raise ValueError("Invalid value for `facility_id`, must not be `None`")  # noqa: E501

        self._facility_id = facility_id

    @property
    def rack_id(self):
        """Gets the rack_id of this ServerCreate.

        ID of the rack where the server is installed  # noqa: E501

        :return: The rack_id of this ServerCreate.
        :rtype: str
        """
        return self._rack_id

    @rack_id.setter
    def rack_id(self, rack_id):
        """Sets the rack_id of this ServerCreate.

        ID of the rack where the server is installed  # noqa: E501

        :param rack_id: The rack_id of this ServerCreate.
        :type rack_id: str
        """
        if rack_id is None:
            raise ValueError("Invalid value for `rack_id`, must not be `None`")  # noqa: E501

        self._rack_id = rack_id

    @property
    def impact_assessment(self):
        """Gets the impact_assessment of this ServerCreate.


        :return: The impact_assessment of this ServerCreate.
        :rtype: ServerImpactAssessment
        """
        return self._impact_assessment

    @impact_assessment.setter
    def impact_assessment(self, impact_assessment):
        """Sets the impact_assessment of this ServerCreate.


        :param impact_assessment: The impact_assessment of this ServerCreate.
        :type impact_assessment: ServerImpactAssessment
        """

        self._impact_assessment = impact_assessment

    @property
    def rated_power(self):
        """Gets the rated_power of this ServerCreate.

        Rated power in kW  # noqa: E501

        :return: The rated_power of this ServerCreate.
        :rtype: float
        """
        return self._rated_power

    @rated_power.setter
    def rated_power(self, rated_power):
        """Sets the rated_power of this ServerCreate.

        Rated power in kW  # noqa: E501

        :param rated_power: The rated_power of this ServerCreate.
        :type rated_power: float
        """

        self._rated_power = rated_power

    @property
    def total_cpu_sockets(self):
        """Gets the total_cpu_sockets of this ServerCreate.

        Total number of CPU sockets  # noqa: E501

        :return: The total_cpu_sockets of this ServerCreate.
        :rtype: int
        """
        return self._total_cpu_sockets

    @total_cpu_sockets.setter
    def total_cpu_sockets(self, total_cpu_sockets):
        """Sets the total_cpu_sockets of this ServerCreate.

        Total number of CPU sockets  # noqa: E501

        :param total_cpu_sockets: The total_cpu_sockets of this ServerCreate.
        :type total_cpu_sockets: int
        """
        if total_cpu_sockets is not None and total_cpu_sockets < 1:  # noqa: E501
            raise ValueError("Invalid value for `total_cpu_sockets`, must be a value greater than or equal to `1`")  # noqa: E501

        self._total_cpu_sockets = total_cpu_sockets

    @property
    def expected_lifetime(self):
        """Gets the expected_lifetime of this ServerCreate.

        Expected lifetime of the server hardware  # noqa: E501

        :return: The expected_lifetime of this ServerCreate.
        :rtype: int
        """
        return self._expected_lifetime

    @expected_lifetime.setter
    def expected_lifetime(self, expected_lifetime):
        """Sets the expected_lifetime of this ServerCreate.

        Expected lifetime of the server hardware  # noqa: E501

        :param expected_lifetime: The expected_lifetime of this ServerCreate.
        :type expected_lifetime: int
        """
        if expected_lifetime is None:
            raise ValueError("Invalid value for `expected_lifetime`, must not be `None`")  # noqa: E501
        if expected_lifetime is not None and expected_lifetime > 20:  # noqa: E501
            raise ValueError("Invalid value for `expected_lifetime`, must be a value less than or equal to `20`")  # noqa: E501
        if expected_lifetime is not None and expected_lifetime < 1:  # noqa: E501
            raise ValueError("Invalid value for `expected_lifetime`, must be a value greater than or equal to `1`")  # noqa: E501

        self._expected_lifetime = expected_lifetime

    @property
    def installed_cpus(self):
        """Gets the installed_cpus of this ServerCreate.

        Array of installed CPUs  # noqa: E501

        :return: The installed_cpus of this ServerCreate.
        :rtype: List[CPU]
        """
        return self._installed_cpus

    @installed_cpus.setter
    def installed_cpus(self, installed_cpus):
        """Sets the installed_cpus of this ServerCreate.

        Array of installed CPUs  # noqa: E501

        :param installed_cpus: The installed_cpus of this ServerCreate.
        :type installed_cpus: List[CPU]
        """

        self._installed_cpus = installed_cpus

    @property
    def number_of_psus(self):
        """Gets the number_of_psus of this ServerCreate.

        Number of power supply units  # noqa: E501

        :return: The number_of_psus of this ServerCreate.
        :rtype: int
        """
        return self._number_of_psus

    @number_of_psus.setter
    def number_of_psus(self, number_of_psus):
        """Sets the number_of_psus of this ServerCreate.

        Number of power supply units  # noqa: E501

        :param number_of_psus: The number_of_psus of this ServerCreate.
        :type number_of_psus: int
        """
        if number_of_psus is not None and number_of_psus < 1:  # noqa: E501
            raise ValueError("Invalid value for `number_of_psus`, must be a value greater than or equal to `1`")  # noqa: E501

        self._number_of_psus = number_of_psus

    @property
    def total_installed_memory(self):
        """Gets the total_installed_memory of this ServerCreate.

        Total installed memory in GB  # noqa: E501

        :return: The total_installed_memory of this ServerCreate.
        :rtype: int
        """
        return self._total_installed_memory

    @total_installed_memory.setter
    def total_installed_memory(self, total_installed_memory):
        """Sets the total_installed_memory of this ServerCreate.

        Total installed memory in GB  # noqa: E501

        :param total_installed_memory: The total_installed_memory of this ServerCreate.
        :type total_installed_memory: int
        """

        self._total_installed_memory = total_installed_memory

    @property
    def number_of_memory_units(self):
        """Gets the number_of_memory_units of this ServerCreate.

        Number of memory units installed  # noqa: E501

        :return: The number_of_memory_units of this ServerCreate.
        :rtype: int
        """
        return self._number_of_memory_units

    @number_of_memory_units.setter
    def number_of_memory_units(self, number_of_memory_units):
        """Sets the number_of_memory_units of this ServerCreate.

        Number of memory units installed  # noqa: E501

        :param number_of_memory_units: The number_of_memory_units of this ServerCreate.
        :type number_of_memory_units: int
        """

        self._number_of_memory_units = number_of_memory_units

    @property
    def storage_devices(self):
        """Gets the storage_devices of this ServerCreate.

        Array of installed storage devices  # noqa: E501

        :return: The storage_devices of this ServerCreate.
        :rtype: List[StorageDevice]
        """
        return self._storage_devices

    @storage_devices.setter
    def storage_devices(self, storage_devices):
        """Sets the storage_devices of this ServerCreate.

        Array of installed storage devices  # noqa: E501

        :param storage_devices: The storage_devices of this ServerCreate.
        :type storage_devices: List[StorageDevice]
        """

        self._storage_devices = storage_devices

    @property
    def installed_gpus(self):
        """Gets the installed_gpus of this ServerCreate.

        Array of installed GPUs  # noqa: E501

        :return: The installed_gpus of this ServerCreate.
        :rtype: List[GPU]
        """
        return self._installed_gpus

    @installed_gpus.setter
    def installed_gpus(self, installed_gpus):
        """Sets the installed_gpus of this ServerCreate.

        Array of installed GPUs  # noqa: E501

        :param installed_gpus: The installed_gpus of this ServerCreate.
        :type installed_gpus: List[GPU]
        """

        self._installed_gpus = installed_gpus

    @property
    def installed_fpgas(self):
        """Gets the installed_fpgas of this ServerCreate.

        Array of installed FPGAs  # noqa: E501

        :return: The installed_fpgas of this ServerCreate.
        :rtype: List[FPGA]
        """
        return self._installed_fpgas

    @installed_fpgas.setter
    def installed_fpgas(self, installed_fpgas):
        """Sets the installed_fpgas of this ServerCreate.

        Array of installed FPGAs  # noqa: E501

        :param installed_fpgas: The installed_fpgas of this ServerCreate.
        :type installed_fpgas: List[FPGA]
        """

        self._installed_fpgas = installed_fpgas

    @property
    def product_passport(self):
        """Gets the product_passport of this ServerCreate.

        LCA product passport data  # noqa: E501

        :return: The product_passport of this ServerCreate.
        :rtype: object
        """
        return self._product_passport

    @product_passport.setter
    def product_passport(self, product_passport):
        """Sets the product_passport of this ServerCreate.

        LCA product passport data  # noqa: E501

        :param product_passport: The product_passport of this ServerCreate.
        :type product_passport: object
        """

        self._product_passport = product_passport

    @property
    def cooling_type(self):
        """Gets the cooling_type of this ServerCreate.

        Type of cooling system used for this server  # noqa: E501

        :return: The cooling_type of this ServerCreate.
        :rtype: str
        """
        return self._cooling_type

    @cooling_type.setter
    def cooling_type(self, cooling_type):
        """Sets the cooling_type of this ServerCreate.

        Type of cooling system used for this server  # noqa: E501

        :param cooling_type: The cooling_type of this ServerCreate.
        :type cooling_type: str
        """
        allowed_values = ["direct-to-chip", "immersion", "back-door-liquid", "back-door-fan", "air"]  # noqa: E501
        if cooling_type not in allowed_values:
            raise ValueError(
                "Invalid value for `cooling_type` ({0}), must be one of {1}"
                .format(cooling_type, allowed_values)
            )

        self._cooling_type = cooling_type

    @property
    def description(self):
        """Gets the description of this ServerCreate.

        Textual description ob the facility for informational purposes  # noqa: E501

        :return: The description of this ServerCreate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ServerCreate.

        Textual description ob the facility for informational purposes  # noqa: E501

        :param description: The description of this ServerCreate.
        :type description: str
        """

        self._description = description
