# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.cpu import CPU
from nadiki_registrar.models.fpga import FPGA
from nadiki_registrar.models.gpu import GPU
from nadiki_registrar.models.server_time_series_config import ServerTimeSeriesConfig
from nadiki_registrar.models.storage_device import StorageDevice
from nadiki_registrar import util

from nadiki_registrar.models.cpu import CPU  # noqa: E501
from nadiki_registrar.models.fpga import FPGA  # noqa: E501
from nadiki_registrar.models.gpu import GPU  # noqa: E501
from nadiki_registrar.models.server_time_series_config import ServerTimeSeriesConfig  # noqa: E501
from nadiki_registrar.models.storage_device import StorageDevice  # noqa: E501

class ServerResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, facility_id=None, rack_id=None, rated_power=None, total_cpu_sockets=2, installed_cpus=None, number_of_psus=2, total_installed_memory=None, number_of_memory_units=None, storage_devices=None, installed_gpus=None, installed_fpgas=None, product_passport=None, cooling_type='air', id=None, time_series_config=None, created_at=None, updated_at=None):  # noqa: E501
        """ServerResponse - a model defined in OpenAPI

        :param facility_id: The facility_id of this ServerResponse.  # noqa: E501
        :type facility_id: str
        :param rack_id: The rack_id of this ServerResponse.  # noqa: E501
        :type rack_id: str
        :param rated_power: The rated_power of this ServerResponse.  # noqa: E501
        :type rated_power: float
        :param total_cpu_sockets: The total_cpu_sockets of this ServerResponse.  # noqa: E501
        :type total_cpu_sockets: int
        :param installed_cpus: The installed_cpus of this ServerResponse.  # noqa: E501
        :type installed_cpus: List[CPU]
        :param number_of_psus: The number_of_psus of this ServerResponse.  # noqa: E501
        :type number_of_psus: int
        :param total_installed_memory: The total_installed_memory of this ServerResponse.  # noqa: E501
        :type total_installed_memory: int
        :param number_of_memory_units: The number_of_memory_units of this ServerResponse.  # noqa: E501
        :type number_of_memory_units: int
        :param storage_devices: The storage_devices of this ServerResponse.  # noqa: E501
        :type storage_devices: List[StorageDevice]
        :param installed_gpus: The installed_gpus of this ServerResponse.  # noqa: E501
        :type installed_gpus: List[GPU]
        :param installed_fpgas: The installed_fpgas of this ServerResponse.  # noqa: E501
        :type installed_fpgas: List[FPGA]
        :param product_passport: The product_passport of this ServerResponse.  # noqa: E501
        :type product_passport: object
        :param cooling_type: The cooling_type of this ServerResponse.  # noqa: E501
        :type cooling_type: str
        :param id: The id of this ServerResponse.  # noqa: E501
        :type id: str
        :param time_series_config: The time_series_config of this ServerResponse.  # noqa: E501
        :type time_series_config: ServerTimeSeriesConfig
        :param created_at: The created_at of this ServerResponse.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this ServerResponse.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'facility_id': str,
            'rack_id': str,
            'rated_power': float,
            'total_cpu_sockets': int,
            'installed_cpus': List[CPU],
            'number_of_psus': int,
            'total_installed_memory': int,
            'number_of_memory_units': int,
            'storage_devices': List[StorageDevice],
            'installed_gpus': List[GPU],
            'installed_fpgas': List[FPGA],
            'product_passport': object,
            'cooling_type': str,
            'id': str,
            'time_series_config': ServerTimeSeriesConfig,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'facility_id': 'facility_id',
            'rack_id': 'rack_id',
            'rated_power': 'rated_power',
            'total_cpu_sockets': 'total_cpu_sockets',
            'installed_cpus': 'installed_cpus',
            'number_of_psus': 'number_of_psus',
            'total_installed_memory': 'total_installed_memory',
            'number_of_memory_units': 'number_of_memory_units',
            'storage_devices': 'storage_devices',
            'installed_gpus': 'installed_gpus',
            'installed_fpgas': 'installed_fpgas',
            'product_passport': 'product_passport',
            'cooling_type': 'cooling_type',
            'id': 'id',
            'time_series_config': 'timeSeriesConfig',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._facility_id = facility_id
        self._rack_id = rack_id
        self._rated_power = rated_power
        self._total_cpu_sockets = total_cpu_sockets
        self._installed_cpus = installed_cpus
        self._number_of_psus = number_of_psus
        self._total_installed_memory = total_installed_memory
        self._number_of_memory_units = number_of_memory_units
        self._storage_devices = storage_devices
        self._installed_gpus = installed_gpus
        self._installed_fpgas = installed_fpgas
        self._product_passport = product_passport
        self._cooling_type = cooling_type
        self._id = id
        self._time_series_config = time_series_config
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'ServerResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerResponse of this ServerResponse.  # noqa: E501
        :rtype: ServerResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def facility_id(self):
        """Gets the facility_id of this ServerResponse.

        ID of the facility where the server is located  # noqa: E501

        :return: The facility_id of this ServerResponse.
        :rtype: str
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """Sets the facility_id of this ServerResponse.

        ID of the facility where the server is located  # noqa: E501

        :param facility_id: The facility_id of this ServerResponse.
        :type facility_id: str
        """
        if facility_id is None:
            raise ValueError("Invalid value for `facility_id`, must not be `None`")  # noqa: E501

        self._facility_id = facility_id

    @property
    def rack_id(self):
        """Gets the rack_id of this ServerResponse.

        ID of the rack where the server is installed  # noqa: E501

        :return: The rack_id of this ServerResponse.
        :rtype: str
        """
        return self._rack_id

    @rack_id.setter
    def rack_id(self, rack_id):
        """Sets the rack_id of this ServerResponse.

        ID of the rack where the server is installed  # noqa: E501

        :param rack_id: The rack_id of this ServerResponse.
        :type rack_id: str
        """
        if rack_id is None:
            raise ValueError("Invalid value for `rack_id`, must not be `None`")  # noqa: E501

        self._rack_id = rack_id

    @property
    def rated_power(self):
        """Gets the rated_power of this ServerResponse.

        Rated power in kW  # noqa: E501

        :return: The rated_power of this ServerResponse.
        :rtype: float
        """
        return self._rated_power

    @rated_power.setter
    def rated_power(self, rated_power):
        """Sets the rated_power of this ServerResponse.

        Rated power in kW  # noqa: E501

        :param rated_power: The rated_power of this ServerResponse.
        :type rated_power: float
        """

        self._rated_power = rated_power

    @property
    def total_cpu_sockets(self):
        """Gets the total_cpu_sockets of this ServerResponse.

        Total number of CPU sockets  # noqa: E501

        :return: The total_cpu_sockets of this ServerResponse.
        :rtype: int
        """
        return self._total_cpu_sockets

    @total_cpu_sockets.setter
    def total_cpu_sockets(self, total_cpu_sockets):
        """Sets the total_cpu_sockets of this ServerResponse.

        Total number of CPU sockets  # noqa: E501

        :param total_cpu_sockets: The total_cpu_sockets of this ServerResponse.
        :type total_cpu_sockets: int
        """
        if total_cpu_sockets is not None and total_cpu_sockets < 1:  # noqa: E501
            raise ValueError("Invalid value for `total_cpu_sockets`, must be a value greater than or equal to `1`")  # noqa: E501

        self._total_cpu_sockets = total_cpu_sockets

    @property
    def installed_cpus(self):
        """Gets the installed_cpus of this ServerResponse.

        Array of installed CPUs  # noqa: E501

        :return: The installed_cpus of this ServerResponse.
        :rtype: List[CPU]
        """
        return self._installed_cpus

    @installed_cpus.setter
    def installed_cpus(self, installed_cpus):
        """Sets the installed_cpus of this ServerResponse.

        Array of installed CPUs  # noqa: E501

        :param installed_cpus: The installed_cpus of this ServerResponse.
        :type installed_cpus: List[CPU]
        """

        self._installed_cpus = installed_cpus

    @property
    def number_of_psus(self):
        """Gets the number_of_psus of this ServerResponse.

        Number of power supply units  # noqa: E501

        :return: The number_of_psus of this ServerResponse.
        :rtype: int
        """
        return self._number_of_psus

    @number_of_psus.setter
    def number_of_psus(self, number_of_psus):
        """Sets the number_of_psus of this ServerResponse.

        Number of power supply units  # noqa: E501

        :param number_of_psus: The number_of_psus of this ServerResponse.
        :type number_of_psus: int
        """
        if number_of_psus is not None and number_of_psus < 1:  # noqa: E501
            raise ValueError("Invalid value for `number_of_psus`, must be a value greater than or equal to `1`")  # noqa: E501

        self._number_of_psus = number_of_psus

    @property
    def total_installed_memory(self):
        """Gets the total_installed_memory of this ServerResponse.

        Total installed memory in GB  # noqa: E501

        :return: The total_installed_memory of this ServerResponse.
        :rtype: int
        """
        return self._total_installed_memory

    @total_installed_memory.setter
    def total_installed_memory(self, total_installed_memory):
        """Sets the total_installed_memory of this ServerResponse.

        Total installed memory in GB  # noqa: E501

        :param total_installed_memory: The total_installed_memory of this ServerResponse.
        :type total_installed_memory: int
        """

        self._total_installed_memory = total_installed_memory

    @property
    def number_of_memory_units(self):
        """Gets the number_of_memory_units of this ServerResponse.

        Number of memory units installed  # noqa: E501

        :return: The number_of_memory_units of this ServerResponse.
        :rtype: int
        """
        return self._number_of_memory_units

    @number_of_memory_units.setter
    def number_of_memory_units(self, number_of_memory_units):
        """Sets the number_of_memory_units of this ServerResponse.

        Number of memory units installed  # noqa: E501

        :param number_of_memory_units: The number_of_memory_units of this ServerResponse.
        :type number_of_memory_units: int
        """

        self._number_of_memory_units = number_of_memory_units

    @property
    def storage_devices(self):
        """Gets the storage_devices of this ServerResponse.

        Array of installed storage devices  # noqa: E501

        :return: The storage_devices of this ServerResponse.
        :rtype: List[StorageDevice]
        """
        return self._storage_devices

    @storage_devices.setter
    def storage_devices(self, storage_devices):
        """Sets the storage_devices of this ServerResponse.

        Array of installed storage devices  # noqa: E501

        :param storage_devices: The storage_devices of this ServerResponse.
        :type storage_devices: List[StorageDevice]
        """

        self._storage_devices = storage_devices

    @property
    def installed_gpus(self):
        """Gets the installed_gpus of this ServerResponse.

        Array of installed GPUs  # noqa: E501

        :return: The installed_gpus of this ServerResponse.
        :rtype: List[GPU]
        """
        return self._installed_gpus

    @installed_gpus.setter
    def installed_gpus(self, installed_gpus):
        """Sets the installed_gpus of this ServerResponse.

        Array of installed GPUs  # noqa: E501

        :param installed_gpus: The installed_gpus of this ServerResponse.
        :type installed_gpus: List[GPU]
        """

        self._installed_gpus = installed_gpus

    @property
    def installed_fpgas(self):
        """Gets the installed_fpgas of this ServerResponse.

        Array of installed FPGAs  # noqa: E501

        :return: The installed_fpgas of this ServerResponse.
        :rtype: List[FPGA]
        """
        return self._installed_fpgas

    @installed_fpgas.setter
    def installed_fpgas(self, installed_fpgas):
        """Sets the installed_fpgas of this ServerResponse.

        Array of installed FPGAs  # noqa: E501

        :param installed_fpgas: The installed_fpgas of this ServerResponse.
        :type installed_fpgas: List[FPGA]
        """

        self._installed_fpgas = installed_fpgas

    @property
    def product_passport(self):
        """Gets the product_passport of this ServerResponse.

        LCA product passport data  # noqa: E501

        :return: The product_passport of this ServerResponse.
        :rtype: object
        """
        return self._product_passport

    @product_passport.setter
    def product_passport(self, product_passport):
        """Sets the product_passport of this ServerResponse.

        LCA product passport data  # noqa: E501

        :param product_passport: The product_passport of this ServerResponse.
        :type product_passport: object
        """

        self._product_passport = product_passport

    @property
    def cooling_type(self):
        """Gets the cooling_type of this ServerResponse.

        Type of cooling system used for this server  # noqa: E501

        :return: The cooling_type of this ServerResponse.
        :rtype: str
        """
        return self._cooling_type

    @cooling_type.setter
    def cooling_type(self, cooling_type):
        """Sets the cooling_type of this ServerResponse.

        Type of cooling system used for this server  # noqa: E501

        :param cooling_type: The cooling_type of this ServerResponse.
        :type cooling_type: str
        """
        allowed_values = ["direct-to-chip", "immersion", "back-door-liquid", "back-door-fan", "air"]  # noqa: E501
        if cooling_type not in allowed_values:
            raise ValueError(
                "Invalid value for `cooling_type` ({0}), must be one of {1}"
                .format(cooling_type, allowed_values)
            )

        self._cooling_type = cooling_type

    @property
    def id(self):
        """Gets the id of this ServerResponse.

        Unique server identifier (format SERVER-[FACILITY_ID]-[RACK_ID]-[SERVER_ID])  # noqa: E501

        :return: The id of this ServerResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ServerResponse.

        Unique server identifier (format SERVER-[FACILITY_ID]-[RACK_ID]-[SERVER_ID])  # noqa: E501

        :param id: The id of this ServerResponse.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def time_series_config(self):
        """Gets the time_series_config of this ServerResponse.


        :return: The time_series_config of this ServerResponse.
        :rtype: ServerTimeSeriesConfig
        """
        return self._time_series_config

    @time_series_config.setter
    def time_series_config(self, time_series_config):
        """Sets the time_series_config of this ServerResponse.


        :param time_series_config: The time_series_config of this ServerResponse.
        :type time_series_config: ServerTimeSeriesConfig
        """
        if time_series_config is None:
            raise ValueError("Invalid value for `time_series_config`, must not be `None`")  # noqa: E501

        self._time_series_config = time_series_config

    @property
    def created_at(self):
        """Gets the created_at of this ServerResponse.


        :return: The created_at of this ServerResponse.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ServerResponse.


        :param created_at: The created_at of this ServerResponse.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ServerResponse.


        :return: The updated_at of this ServerResponse.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ServerResponse.


        :param updated_at: The updated_at of this ServerResponse.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
