# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.server_time_series_data_point import ServerTimeSeriesDataPoint
from nadiki_registrar import util

from nadiki_registrar.models.server_time_series_data_point import ServerTimeSeriesDataPoint  # noqa: E501

class ServerTimeSeriesConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, endpoint=None, org=None, bucket=None, token=None, data_points=None):  # noqa: E501
        """ServerTimeSeriesConfig - a model defined in OpenAPI

        :param endpoint: The endpoint of this ServerTimeSeriesConfig.  # noqa: E501
        :type endpoint: str
        :param org: The org of this ServerTimeSeriesConfig.  # noqa: E501
        :type org: str
        :param bucket: The bucket of this ServerTimeSeriesConfig.  # noqa: E501
        :type bucket: str
        :param token: The token of this ServerTimeSeriesConfig.  # noqa: E501
        :type token: str
        :param data_points: The data_points of this ServerTimeSeriesConfig.  # noqa: E501
        :type data_points: List[ServerTimeSeriesDataPoint]
        """
        self.openapi_types = {
            'endpoint': str,
            'org': str,
            'bucket': str,
            'token': str,
            'data_points': List[ServerTimeSeriesDataPoint]
        }

        self.attribute_map = {
            'endpoint': 'endpoint',
            'org': 'org',
            'bucket': 'bucket',
            'token': 'token',
            'data_points': 'dataPoints'
        }

        self._endpoint = endpoint
        self._org = org
        self._bucket = bucket
        self._token = token
        self._data_points = data_points

    @classmethod
    def from_dict(cls, dikt) -> 'ServerTimeSeriesConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerTimeSeriesConfig of this ServerTimeSeriesConfig.  # noqa: E501
        :rtype: ServerTimeSeriesConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def endpoint(self):
        """Gets the endpoint of this ServerTimeSeriesConfig.

        InfluxDB endpoint URL with port number  # noqa: E501

        :return: The endpoint of this ServerTimeSeriesConfig.
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this ServerTimeSeriesConfig.

        InfluxDB endpoint URL with port number  # noqa: E501

        :param endpoint: The endpoint of this ServerTimeSeriesConfig.
        :type endpoint: str
        """
        if endpoint is None:
            raise ValueError("Invalid value for `endpoint`, must not be `None`")  # noqa: E501

        self._endpoint = endpoint

    @property
    def org(self):
        """Gets the org of this ServerTimeSeriesConfig.

        InfluxDB organization to use  # noqa: E501

        :return: The org of this ServerTimeSeriesConfig.
        :rtype: str
        """
        return self._org

    @org.setter
    def org(self, org):
        """Sets the org of this ServerTimeSeriesConfig.

        InfluxDB organization to use  # noqa: E501

        :param org: The org of this ServerTimeSeriesConfig.
        :type org: str
        """
        if org is None:
            raise ValueError("Invalid value for `org`, must not be `None`")  # noqa: E501

        self._org = org

    @property
    def bucket(self):
        """Gets the bucket of this ServerTimeSeriesConfig.

        InfluxDB bucket to send data to  # noqa: E501

        :return: The bucket of this ServerTimeSeriesConfig.
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket):
        """Sets the bucket of this ServerTimeSeriesConfig.

        InfluxDB bucket to send data to  # noqa: E501

        :param bucket: The bucket of this ServerTimeSeriesConfig.
        :type bucket: str
        """
        if bucket is None:
            raise ValueError("Invalid value for `bucket`, must not be `None`")  # noqa: E501

        self._bucket = bucket

    @property
    def token(self):
        """Gets the token of this ServerTimeSeriesConfig.

        InfluxDB token to use for authentication  # noqa: E501

        :return: The token of this ServerTimeSeriesConfig.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this ServerTimeSeriesConfig.

        InfluxDB token to use for authentication  # noqa: E501

        :param token: The token of this ServerTimeSeriesConfig.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def data_points(self):
        """Gets the data_points of this ServerTimeSeriesConfig.

        List of time series metrics available for streaming  # noqa: E501

        :return: The data_points of this ServerTimeSeriesConfig.
        :rtype: List[ServerTimeSeriesDataPoint]
        """
        return self._data_points

    @data_points.setter
    def data_points(self, data_points):
        """Sets the data_points of this ServerTimeSeriesConfig.

        List of time series metrics available for streaming  # noqa: E501

        :param data_points: The data_points of this ServerTimeSeriesConfig.
        :type data_points: List[ServerTimeSeriesDataPoint]
        """
        if data_points is None:
            raise ValueError("Invalid value for `data_points`, must not be `None`")  # noqa: E501

        self._data_points = data_points
