# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nadiki_registrar.models.base_model_ import Model
from nadiki_registrar.models.server_time_series_data_point_tags import ServerTimeSeriesDataPointTags
from nadiki_registrar import util

from nadiki_registrar.models.server_time_series_data_point_tags import ServerTimeSeriesDataPointTags  # noqa: E501

class ServerTimeSeriesDataPoint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, measurement=None, field=None, granularity_seconds=None, tags=None):  # noqa: E501
        """ServerTimeSeriesDataPoint - a model defined in OpenAPI

        :param measurement: The measurement of this ServerTimeSeriesDataPoint.  # noqa: E501
        :type measurement: str
        :param field: The field of this ServerTimeSeriesDataPoint.  # noqa: E501
        :type field: str
        :param granularity_seconds: The granularity_seconds of this ServerTimeSeriesDataPoint.  # noqa: E501
        :type granularity_seconds: int
        :param tags: The tags of this ServerTimeSeriesDataPoint.  # noqa: E501
        :type tags: ServerTimeSeriesDataPointTags
        """
        self.openapi_types = {
            'measurement': str,
            'field': str,
            'granularity_seconds': int,
            'tags': ServerTimeSeriesDataPointTags
        }

        self.attribute_map = {
            'measurement': 'measurement',
            'field': 'field',
            'granularity_seconds': 'granularitySeconds',
            'tags': 'tags'
        }

        self._measurement = measurement
        self._field = field
        self._granularity_seconds = granularity_seconds
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'ServerTimeSeriesDataPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerTimeSeriesDataPoint of this ServerTimeSeriesDataPoint.  # noqa: E501
        :rtype: ServerTimeSeriesDataPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def measurement(self):
        """Gets the measurement of this ServerTimeSeriesDataPoint.

        Name of the Influx measurement  # noqa: E501

        :return: The measurement of this ServerTimeSeriesDataPoint.
        :rtype: str
        """
        return self._measurement

    @measurement.setter
    def measurement(self, measurement):
        """Sets the measurement of this ServerTimeSeriesDataPoint.

        Name of the Influx measurement  # noqa: E501

        :param measurement: The measurement of this ServerTimeSeriesDataPoint.
        :type measurement: str
        """
        allowed_values = ["facility", "rack", "server"]  # noqa: E501
        if measurement not in allowed_values:
            raise ValueError(
                "Invalid value for `measurement` ({0}), must be one of {1}"
                .format(measurement, allowed_values)
            )

        self._measurement = measurement

    @property
    def field(self):
        """Gets the field of this ServerTimeSeriesDataPoint.

        Metric name to be written to InfluxDB (derived from target_metric in the mapping)  # noqa: E501

        :return: The field of this ServerTimeSeriesDataPoint.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this ServerTimeSeriesDataPoint.

        Metric name to be written to InfluxDB (derived from target_metric in the mapping)  # noqa: E501

        :param field: The field of this ServerTimeSeriesDataPoint.
        :type field: str
        """
        if field is None:
            raise ValueError("Invalid value for `field`, must not be `None`")  # noqa: E501

        self._field = field

    @property
    def granularity_seconds(self):
        """Gets the granularity_seconds of this ServerTimeSeriesDataPoint.

        Time series data granularity in seconds (from measurement_interval in the mapping)  # noqa: E501

        :return: The granularity_seconds of this ServerTimeSeriesDataPoint.
        :rtype: int
        """
        return self._granularity_seconds

    @granularity_seconds.setter
    def granularity_seconds(self, granularity_seconds):
        """Sets the granularity_seconds of this ServerTimeSeriesDataPoint.

        Time series data granularity in seconds (from measurement_interval in the mapping)  # noqa: E501

        :param granularity_seconds: The granularity_seconds of this ServerTimeSeriesDataPoint.
        :type granularity_seconds: int
        """
        if granularity_seconds is None:
            raise ValueError("Invalid value for `granularity_seconds`, must not be `None`")  # noqa: E501

        self._granularity_seconds = granularity_seconds

    @property
    def tags(self):
        """Gets the tags of this ServerTimeSeriesDataPoint.


        :return: The tags of this ServerTimeSeriesDataPoint.
        :rtype: ServerTimeSeriesDataPointTags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ServerTimeSeriesDataPoint.


        :param tags: The tags of this ServerTimeSeriesDataPoint.
        :type tags: ServerTimeSeriesDataPointTags
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags
